# Generated by Django 4.2.30 on 2026-04-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailmessage_order_emailmessage_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
