# Generated by Django 4.2.30 on 2026-04-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
