# Generated by Django 4.2.30 on 2026-04-30 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0004_teammember_permissions_alter_teammember_user'),
        ('stores', '0001_initial'),
        ('emails', '0006_emailattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThreadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.EmailField(max_length=254)),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_threads', to='teamapp.teammember')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_assignments', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'contact')},
            },
        ),
    ]
