# Generated by Django 4.2.30 on 2026-05-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0004_teammember_permissions_alter_teammember_user'),
        ('emails', '0008_emailthreadassignment_is_resolved_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailthreadassignment',
            name='co_assignees',
            field=models.ManyToManyField(blank=True, related_name='co_assigned_threads', to='teamapp.teammember'),
        ),
    ]
