# Generated by Django 4.2.30 on 2026-05-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_add_co_assignees_to_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='ai_auto_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='ai_auto_suggest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='ai_include_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='ai_language',
            field=models.CharField(default='english', max_length=50),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='ai_tone',
            field=models.CharField(default='friendly', max_length=50),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='auto_close_after_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='auto_mark_read_on_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='fetch_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='mark_read_in_gmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='notify_assigned_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='notify_browser',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='notify_sound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='notify_unread_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='show_cc_bcc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='sync_folder',
            field=models.CharField(default='INBOX', max_length=100),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='sync_on_tab_focus',
            field=models.BooleanField(default=True),
        ),
    ]
