# Generated by Django 4.2.30 on 2026-05-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('emails', '0010_emailaccount_ai_auto_draft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Template', max_length=255)),
                ('category', models.CharField(choices=[('order', 'Order Confirmation'), ('shipping', 'Shipping Notification'), ('cancelled', 'Order Cancelled'), ('failed', 'Payment Failed'), ('refund', 'Refund'), ('welcome', 'Welcome'), ('followup', 'Follow-up'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('bcc_emails', models.JSONField(blank=True, default=list)),
                ('use_default_signature', models.BooleanField(default=True)),
                ('custom_signature', models.TextField(blank=True, default='')),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('preheader', models.CharField(blank=True, default='', max_length=255)),
                ('body_html', models.TextField(blank=True, default='')),
                ('footer', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual Only'), ('order_placed', 'Order Placed'), ('tracking_added', 'Tracking Added'), ('order_cancelled', 'Order Cancelled'), ('payment_failed', 'Payment Failed'), ('order_delivered', 'Order Delivered'), ('no_activity_7d', '7 Days No Activity')], default='manual', max_length=50)),
                ('trigger_delay_minutes', models.IntegerField(default=0)),
                ('working_hours_only', models.BooleanField(default=False)),
                ('throttle_per_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='stores.store')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
