# Generated by Django 4.2.30 on 2026-05-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='is_category_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(choices=[('order', 'Order Confirmation'), ('shipping', 'Shipping Notification'), ('cancelled', 'Order Cancelled'), ('failed', 'Payment Failed'), ('refund', 'Refund'), ('dispute', 'Dispute'), ('welcome', 'Welcome'), ('followup', 'Follow-up'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
    ]
