# Generated by Django 4.2.30 on 2026-05-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('emails', '0012_emailtemplate_is_category_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='stores.store'),
        ),
    ]
