# Generated by Django 4.2.30 on 2026-05-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_add_is_global_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='auto_email_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
