# Generated by Django 4.2.30 on 2026-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0015_add_templates_seeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='auth_type',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='oauth_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
