# Generated by Django 4.2.30 on 2026-05-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_user_nullable'),
        ('emails', '0016_add_oauth_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='stores.store'),
        ),
    ]
