# Generated by Django 4.2.30 on 2026-05-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0017_emailaccount_onetomany'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='live_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='sync_interval',
            field=models.IntegerField(default=60),
        ),
    ]
