# Generated by Django 4.2.30 on 2026-05-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0018_add_live_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
