# Generated by Django 4.2.30 on 2026-05-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0019_add_body_html_to_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='ai_custom_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='ai_reply_mode',
            field=models.CharField(choices=[('off', 'Off'), ('suggest', 'Suggest Draft'), ('auto', 'Auto-Send'), ('hybrid', 'Hybrid (auto for simple, suggest for complex)')], default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='ai_use_signature',
            field=models.BooleanField(default=True),
        ),
    ]
