# Generated by Django 4.2.30 on 2026-05-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_user_nullable'),
        ('emails', '0020_add_ai_reply_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Shipping', 'Shipping'), ('Refund', 'Refund'), ('Product', 'Product'), ('Payment', 'Payment'), ('FAQ', 'FAQ'), ('Brand', 'Brand'), ('Support', 'Support'), ('AI', 'AI Behavior'), ('Guardrail', 'Guardrail')], default='FAQ', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('from_wizard', models.BooleanField(default=False)),
                ('order_idx', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_snippets', to='stores.store')),
            ],
            options={
                'ordering': ['order_idx', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AiTrainingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('niche', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='English', max_length=100)),
                ('support_hours', models.CharField(blank=True, default='', max_length=255)),
                ('tones', models.JSONField(blank=True, default=list)),
                ('reply_length', models.CharField(blank=True, default='Medium', max_length=50)),
                ('signoff', models.CharField(blank=True, default='', max_length=255)),
                ('voice_example', models.TextField(blank=True, default='')),
                ('mode', models.CharField(choices=[('auto', 'Fully Automatic'), ('draft', 'Draft & Review'), ('suggest', 'Suggest on Open')], default='draft', max_length=20)),
                ('toggles', models.JSONField(blank=True, default=dict)),
                ('wizard_answers', models.JSONField(blank=True, default=dict)),
                ('wizard_completed_at', models.DateTimeField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_training_profile', to='stores.store')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
