# Generated by Django 4.2.30 on 2026-05-16 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_user_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0021_knowledgesnippet_aitrainingprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiReplyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('edit', 'Admin edited before sending'), ('reject', 'Admin discarded the AI draft'), ('approve', 'Admin sent as-is (positive signal)'), ('complaint', 'Customer complained about a sent reply')], default='edit', max_length=20)),
                ('ai_draft', models.TextField(blank=True, default='')),
                ('final_text', models.TextField(blank=True, default='')),
                ('correction_note', models.TextField(blank=True, default='')),
                ('customer_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('email_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedbacks', to='emails.emailmessage')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reply_feedbacks', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
