# Generated by Django 4.2.30 on 2026-05-21 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0023_emailaccount_gmail_watch_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAiTrainingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_store_url', models.URLField(max_length=600)),
                ('source_store_name', models.CharField(blank=True, default='', max_length=255)),
                ('profile_json', models.JSONField(blank=True, default=dict)),
                ('snippets_json', models.JSONField(blank=True, default=list)),
                ('feedbacks_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_ai_training_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
