# Generated by Django 4.2.30 on 2026-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0024_pendingaitrainingsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesnippet',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='knowledgesnippet',
            name='category',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Refund', 'Refund'), ('Product', 'Product'), ('Payment', 'Payment'), ('FAQ', 'FAQ'), ('Brand', 'Brand'), ('Support', 'Support'), ('AI', 'AI Behavior'), ('Guardrail', 'Guardrail'), ('Disputes', 'Disputes'), ('Address', 'Address Updates'), ('Cancellations', 'Cancellations'), ('OutOfStock', 'Out of Stock'), ('ShippingDelays', 'Shipping Delays'), ('ProductDefects', 'Product Defects'), ('WrongItem', 'Wrong Item Received'), ('PaymentIssues', 'Payment Issues')], default='FAQ', max_length=30),
        ),
    ]
