# Generated by Django 4.2.30 on 2026-05-23 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_store_user_nullable'),
        ('emails', '0025_knowledgesnippet_is_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=12)),
                ('icon', models.CharField(blank=True, default='', max_length=8)),
                ('is_shared', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_labels', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='ai_confidence_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='ai_escalation_category',
            field=models.CharField(blank=True, choices=[('low_confidence', 'Low Confidence'), ('missing_context', 'Missing Context'), ('ambiguous', 'Ambiguous'), ('sensitive', 'Sensitive'), ('policy_conflict', 'Policy Conflict'), ('language', 'Language'), ('manual_request', 'Manual Request'), ('ai_failure', 'AI Failure')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='ai_escalation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='ai_status',
            field=models.CharField(choices=[('auto_handled', 'Auto Handled'), ('review_suggested', 'Review Suggested'), ('needs_human', 'Needs Human')], default='auto_handled', max_length=20),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='resolved_by_human_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailThreadLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.EmailField(max_length=254)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_links', to='emails.emaillabel')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_labels', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'contact'], name='emails_emai_store_i_67524f_idx'), models.Index(fields=['label'], name='emails_emai_label_i_5c2b12_idx')],
                'unique_together': {('store', 'contact', 'label')},
            },
        ),
        migrations.CreateModel(
            name='AiFallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('api_timeout', 'API Timeout'), ('empty_response', 'Empty Response'), ('malformed_output', 'Malformed Output'), ('refused', 'AI Refused'), ('content_filter', 'Content Filter'), ('token_limit', 'Token Limit'), ('network_error', 'Network Error'), ('low_confidence', 'Low Confidence'), ('missing_context', 'Missing Context'), ('sensitive_keyword', 'Sensitive Keyword'), ('manual_request', 'Customer Requested Human'), ('policy_conflict', 'Policy Conflict'), ('other', 'Other')], max_length=30)),
                ('technical_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_logs', to='emails.emailmessage')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_fallback_logs', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'created_at'], name='emails_aifa_store_i_6067d7_idx'), models.Index(fields=['reason'], name='emails_aifa_reason_3ae7f4_idx')],
            },
        ),
    ]
