# Generated by Django 4.2.30 on 2026-05-23 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamapp', '0014_fix_existing_channelmember_joined_at'),
        ('stores', '0002_store_user_nullable'),
        ('emails', '0026_emaillabel_emailmessage_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(blank=True, choices=[('inbox', 'Inbox'), ('unread', 'Unread'), ('needs_human', 'Needs Human'), ('ai_drafts', 'AI Drafts'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('resolved', 'Resolved'), ('refunds', 'Refunds'), ('returns', 'Returns'), ('dispute', 'Dispute'), ('spam', 'Spam'), ('archive', 'Archive')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_assignments', to='teamapp.teammember')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_assignments', to='emails.emaillabel')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_assignments', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'is_active'], name='emails_fold_store_i_9ef4b0_idx'), models.Index(fields=['assigned_to', 'is_active'], name='emails_fold_assigne_e1eff8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='folderassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('label__isnull', True), models.Q(('folder', ''), _negated=True)), fields=('store', 'folder'), name='uniq_active_folder_assign'),
        ),
        migrations.AddConstraint(
            model_name='folderassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('label__isnull', False)), fields=('store', 'label'), name='uniq_active_label_assign'),
        ),
    ]
