# Generated by Django 4.2.30 on 2026-05-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0027_folderassignment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folderassignment',
            name='uniq_active_folder_assign',
        ),
        migrations.RemoveConstraint(
            model_name='folderassignment',
            name='uniq_active_label_assign',
        ),
        migrations.AddIndex(
            model_name='folderassignment',
            index=models.Index(fields=['store', 'folder'], name='emails_fold_store_i_d96884_idx'),
        ),
        migrations.AddIndex(
            model_name='folderassignment',
            index=models.Index(fields=['store', 'label'], name='emails_fold_store_i_744ef6_idx'),
        ),
        migrations.AddConstraint(
            model_name='folderassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('label__isnull', True), models.Q(('folder', ''), _negated=True)), fields=('store', 'folder', 'assigned_to'), name='uniq_folder_member'),
        ),
        migrations.AddConstraint(
            model_name='folderassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('label__isnull', False)), fields=('store', 'label', 'assigned_to'), name='uniq_label_member'),
        ),
    ]
