# Generated by Django 4.2.30 on 2026-05-23 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_user_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamapp', '0014_fix_existing_channelmember_joined_at'),
        ('emails', '0028_remove_folderassignment_uniq_active_folder_assign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThreadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(db_index=True, max_length=255)),
                ('event', models.CharField(choices=[('created', 'Thread created'), ('incoming', 'Incoming message'), ('reply_sent', 'Reply sent'), ('ai_draft', 'AI draft generated'), ('ai_auto_reply', 'AI auto-reply sent'), ('assigned', 'Assigned to member'), ('unassigned', 'Unassigned'), ('co_assigned', 'Co-assignee added'), ('co_unassigned', 'Co-assignee removed'), ('label_added', 'Label added'), ('label_removed', 'Label removed'), ('folder_moved', 'Moved to folder'), ('archived', 'Archived'), ('restored', 'Restored from archive'), ('resolved', 'Marked resolved'), ('unresolved', 'Re-opened'), ('read', 'Marked read'), ('unread', 'Marked unread'), ('needs_human', 'Escalated to Needs Human'), ('handled', 'Marked as handled'), ('note', 'Note added')], db_index=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor_label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_activities_done', to='teamapp.teammember')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_activities_done', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='emails.emailmessage')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_activities', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'contact', '-created_at'], name='emails_emai_store_i_68deb0_idx'), models.Index(fields=['store', 'event'], name='emails_emai_store_i_878045_idx')],
            },
        ),
    ]
