# Generated by Django 4.2.30 on 2026-05-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0030_remove_apple_dark_premium_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(choices=[('order', 'Order Confirmation'), ('shipping', 'Shipping Notification'), ('cancelled', 'Order Cancelled'), ('failed', 'Payment Failed'), ('refund', 'Refund'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('dispute', 'Dispute'), ('welcome', 'Welcome'), ('followup', 'Follow-up'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Manual Only'), ('order_placed', 'Order Placed'), ('tracking_added', 'Tracking Added'), ('order_cancelled', 'Order Cancelled'), ('payment_failed', 'Payment Failed'), ('order_delivered', 'Order Delivered'), ('order_returned', 'Order Returned'), ('no_activity_7d', '7 Days No Activity')], default='manual', max_length=50),
        ),
    ]
