# Generated by Django 4.2.30 on 2026-06-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0033_backfill_new_template_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('new_order', 'New order'), ('failed', 'Failed order')], max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['order_id', 'kind'], name='emails_foun_order_i_461c95_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='foundernotificationlog',
            constraint=models.UniqueConstraint(fields=('order_id', 'kind'), name='uniq_founder_notif_per_order_kind'),
        ),
    ]
