# Generated by Django 4.2.30 on 2026-06-12 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0003_add_shopify_refresh_token'),
        ('emails', '0034_foundernotificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTrainingAutoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='pre_restore', max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('snippets_count', models.PositiveIntegerField(default=0)),
                ('feedbacks_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_training_auto_backups', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_training_auto_backups', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='emails_aitr_store_i_e8ff4f_idx')],
            },
        ),
    ]
