# Generated by Django 4.2.30 on 2026-04-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('tracking_missing', 'Tracking Missing'), ('refund_dispute', 'Refund / Dispute'), ('order_edit', 'Order Edit'), ('new_email', 'New Email'), ('overload', 'Overload Above 90%')], max_length=50)),
                ('assign_to_role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('support', 'Support'), ('order_manager', 'Order Manager'), ('refund_manager', 'Refund Manager'), ('vendor_manager', 'Vendor Manager'), ('email_manager', 'Email Manager')], max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('limited', 'Limited'), ('offline', 'Offline')], default='available', max_length=50)),
                ('workload', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
