# Generated by Django 4.2.30 on 2026-05-06 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_add_delivered_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_store_user_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_products', to='stores.store')),
            ],
            options={
                'ordering': ['product_name'],
                'unique_together': {('store', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='StockVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('sku', models.CharField(blank=True, default='', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='stock.stockproduct')),
            ],
            options={
                'ordering': ['color', 'size'],
                'unique_together': {('product', 'color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='stock.stockvariant')),
            ],
        ),
        migrations.CreateModel(
            name='StockAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Stock Added'), ('deduct', 'Deducted (Order)'), ('reserve', 'Reserved'), ('restore', 'Restored'), ('adjust', 'Manual Adjustment'), ('sync', 'Product Synced')], max_length=20)),
                ('qty_before', models.IntegerField(default=0)),
                ('qty_after', models.IntegerField(default=0)),
                ('actor', models.CharField(default='Admin', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='stock.stockvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
