# Generated by Django 4.2.30 on 2026-05-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
