# Generated by Django 4.2.30 on 2026-05-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_user_nullable'),
        ('orders', '0008_add_delivered_at'),
        ('stock', '0002_stockproduct_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_assignments', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_assignments', to='stock.stockvariant')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('order', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='StockAutoRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_auto_rules', to='stores.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_rules', to='stock.stockvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('store', 'product_id')},
            },
        ),
    ]
