# Generated by Django 4.2.30 on 2026-05-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_add_is_auto_approved'),
        ('stores', '0002_store_user_nullable'),
        ('stock', '0003_stock_order_assignment_and_auto_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStockAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_pricing', 'Pending Vendor Pricing'), ('pending_approval', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_pricing', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('vendor_note', models.TextField(blank=True, default='')),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('approved_by', models.CharField(blank=True, default='', max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='stock.stockproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_stock_assignments', to='stores.store')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_assignments', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorStockAssignmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assigned', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.vendorstockassignment')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_lines', to='stock.stockvariant')),
            ],
            options={
                'ordering': ['variant__size', 'variant__color'],
                'unique_together': {('assignment', 'variant')},
            },
        ),
    ]
