# Generated by Django 4.2.30 on 2026-05-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_vendor_stock_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstockassignment',
            name='estimated_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorstockassignment',
            name='per_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorstockassignment',
            name='resubmission_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorstockassignment',
            name='status',
            field=models.CharField(choices=[('pending_pricing', 'Pending Vendor Quotation'), ('pending_approval', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected — Resubmit'), ('permanently_rejected', 'Permanently Rejected')], default='pending_pricing', max_length=25),
        ),
        migrations.CreateModel(
            name='VendorQuotationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('per_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_days', models.IntegerField()),
                ('vendor_note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('permanently_rejected', 'Permanently Rejected')], default='pending', max_length=25)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='stock.vendorstockassignment')),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
    ]
