# Generated by Django 4.2.30 on 2026-05-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_quotation_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstockassignment',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorstockassignment',
            name='stock_arrived',
            field=models.BooleanField(default=False),
        ),
    ]
