# Generated by Django 4.2.30 on 2026-06-07 08:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=200)),
                ('unread_count_for_tenant', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('cover_emoji', models.CharField(default='🏭', help_text='Emoji shown on the card when no logo.', max_length=8)),
                ('cover_gradient_from', models.CharField(default='#6366f1', max_length=20)),
                ('cover_gradient_to', models.CharField(default='#a855f7', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(default='China', max_length=80)),
                ('headquarters', models.CharField(blank=True, max_length=120)),
                ('founded_year', models.PositiveSmallIntegerField(default=2020)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('min_order_value_usd', models.PositiveIntegerField(default=100)),
                ('typical_lead_days', models.PositiveSmallIntegerField(default=7)),
                ('team_size', models.CharField(blank=True, default='50–100', max_length=40)),
                ('monthly_volume', models.CharField(blank=True, default='1,000+ orders', max_length=80)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('4.80'), max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('on_time_rate_pct', models.PositiveSmallIntegerField(default=95)),
                ('avg_response_hours', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower = appears earlier.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('out', 'Tenant → Partner'), ('in', 'Partner → Tenant')], default='out', max_length=4)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sourcing_partners.partnerconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='partnerconversation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='sourcing_partners.sourcingpartner'),
        ),
        migrations.AddField(
            model_name='partnerconversation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PartnerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='partner_chat/%Y/%m/')),
                ('url', models.URLField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('filesize_bytes', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sourcing_partners.partnermessage')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='partnerconversation',
            unique_together={('tenant', 'partner')},
        ),
    ]
