# Generated by Django 4.2.30 on 2026-06-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing_partners', '0003_tenantwallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerconversation',
            name='typing_partner_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerconversation',
            name='typing_tenant_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerconversation',
            name='unread_count_for_partner',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='partnerconversation',
            index=models.Index(fields=['tenant', '-last_message_at'], name='sourcing_pa_tenant__1c0953_idx'),
        ),
        migrations.AddIndex(
            model_name='partnermessage',
            index=models.Index(fields=['conversation', 'created_at'], name='sourcing_pa_convers_f725e4_idx'),
        ),
    ]
