# Generated by Django 4.2.30 on 2026-06-13 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('total_signups', models.PositiveIntegerField(default=0)),
                ('qualified_signups', models.PositiveIntegerField(default=0)),
                ('reward_granted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('qualified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('qualified_event', models.CharField(blank=True, default='', max_length=40)),
                ('qualified_plan', models.CharField(blank=True, default='', max_length=40)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_attribution', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_up_at'],
                'indexes': [models.Index(fields=['referrer', '-signed_up_at'], name='referrals_r_referre_0d3ca8_idx'), models.Index(fields=['referrer', 'qualified_at'], name='referrals_r_referre_ddc8a4_idx')],
            },
        ),
    ]
