# Generated by Django 4.2.30 on 2026-04-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('limited', 'Limited'), ('offline', 'Offline')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='workload',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('support', 'Support'), ('order_manager', 'Order Manager'), ('refund_manager', 'Refund Manager'), ('vendor_manager', 'Vendor Manager'), ('email_manager', 'Email Manager')], default='support', max_length=50),
        ),
    ]
