# Generated by Django 4.2.30 on 2026-04-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_teammember_status_teammember_workload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('tracking_missing', 'Tracking Missing'), ('refund_dispute', 'Refund / Dispute'), ('new_order', 'New Order'), ('failed_payment', 'Failed Payment')], max_length=50)),
                ('assign_to_role', models.CharField(choices=[('support', 'Support'), ('order_manager', 'Order Manager'), ('refund_manager', 'Refund Manager'), ('vendor_manager', 'Vendor Manager'), ('email_manager', 'Email Manager')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
