# Generated by Django 4.2.30 on 2026-05-05 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamapp', '0005_chatchannel_chatmessage_chatreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannel',
            name='is_dm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='dm_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
