# Generated by Django 4.2.30 on 2026-05-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0008_chatchannel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
