# Generated by Django 4.2.30 on 2026-05-10 13:49

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


def migrate_existing_members(apps, schema_editor):
    """Copy existing chatchannel_members M2M rows into ChannelMember before the old table is dropped."""
    ChatChannel = apps.get_model("teamapp", "ChatChannel")
    ChannelMember = apps.get_model("teamapp", "ChannelMember")
    now = timezone.now()
    existing = []
    for channel in ChatChannel.objects.all():
        for user in channel.members.all():
            existing.append(ChannelMember(channel=channel, user=user, is_active=True))
    # bulk_create ignores duplicates safely
    ChannelMember.objects.bulk_create(existing, ignore_conflicts=True)


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamapp', '0012_add_employee_invitation'),
    ]

    operations = [
        # 1. Create the ChannelMember table
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teamapp.chatchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_member_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('channel', 'user')},
            },
        ),
        # 2. Copy data from old implicit M2M table → ChannelMember (while old table still exists)
        migrations.RunPython(migrate_existing_members, reverse_migrate),
        # 3. Drop the old implicit M2M junction table
        migrations.RemoveField(
            model_name='chatchannel',
            name='members',
        ),
        # 4. Add the new M2M field backed by ChannelMember through model
        migrations.AddField(
            model_name='chatchannel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='channel_memberships', through='teamapp.ChannelMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
