# Generated by Django 4.2.30 on 2026-05-10 13:53

import datetime
from django.db import migrations

EPOCH = datetime.datetime(2020, 1, 1, tzinfo=datetime.timezone.utc)


def backfill_joined_at(apps, schema_editor):
    """
    Members migrated from the old simple M2M got joined_at = migration run time.
    Reset all existing records to EPOCH so they retain full access to historical messages.
    """
    ChannelMember = apps.get_model("teamapp", "ChannelMember")
    ChannelMember.objects.all().update(joined_at=EPOCH)


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0013_channel_member_through'),
    ]

    operations = [
        migrations.RunPython(backfill_joined_at, reverse_backfill),
    ]
