# Generated by Django 4.2.30 on 2026-05-30 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamapp', '0014_fix_existing_channelmember_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannel',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The tenant who owns this channel. NULL for DM channels (is_dm=True).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
