# Generated by Django 4.2.30 on 2026-06-06 09:52
"""
Add the (owner, name) unique constraint that makes duplicate default
chat channels impossible. CRITICAL: this migration MUST dedupe
existing rows BEFORE adding the constraint, otherwise it fails on
any database that already has the bug (which includes production
right now — tenants are seeing triplicate #general / #operations /
#support).

The dedupe step:
  1. Groups non-DM channels by (owner_id, name).
  2. Keeps the oldest (lowest id) as canonical.
  3. Re-parents ChatMessage / ChannelMember / ChatReadReceipt from
     duplicates onto the canonical row, merging where the unique
     (channel, user) pair would otherwise collide.
  4. Deletes the duplicate ChatChannel rows.

Then AddConstraint runs cleanly.
"""
from collections import defaultdict

from django.db import migrations, models


def _dedupe(apps, schema_editor):
    ChatChannel    = apps.get_model("teamapp", "ChatChannel")
    ChannelMember  = apps.get_model("teamapp", "ChannelMember")
    ChatMessage    = apps.get_model("teamapp", "ChatMessage")
    ChatReadReceipt = apps.get_model("teamapp", "ChatReadReceipt")

    groups = defaultdict(list)
    for ch in ChatChannel.objects.filter(is_dm=False).order_by("id"):
        groups[(ch.owner_id, ch.name)].append(ch)

    merged = 0
    for (owner_id, name), channels in groups.items():
        if len(channels) < 2:
            continue
        canonical = channels[0]
        for dup in channels[1:]:
            # Re-parent messages.
            ChatMessage.objects.filter(channel=dup).update(channel=canonical)
            # Re-parent or merge memberships (avoid IntegrityError on the
            # (channel, user) unique pair).
            for m in ChannelMember.objects.filter(channel=dup):
                existing = ChannelMember.objects.filter(
                    channel=canonical, user_id=m.user_id,
                ).first()
                if existing:
                    if m.is_active and not existing.is_active:
                        existing.is_active = True
                        existing.save(update_fields=["is_active"])
                    m.delete()
                else:
                    m.channel = canonical
                    m.save(update_fields=["channel"])
            # Re-parent or merge read receipts.
            for r in ChatReadReceipt.objects.filter(channel=dup):
                existing = ChatReadReceipt.objects.filter(
                    channel=canonical, user_id=r.user_id,
                ).first()
                if existing:
                    if r.last_read_at and (
                        not existing.last_read_at
                        or r.last_read_at > existing.last_read_at
                    ):
                        existing.last_read_at = r.last_read_at
                        existing.save(update_fields=["last_read_at"])
                    r.delete()
                else:
                    r.channel = canonical
                    r.save(update_fields=["channel"])
            dup.delete()
            merged += 1

    if merged:
        print(f"  → merged {merged} duplicate chat channel(s)")


def _noop(apps, schema_editor):
    """The dedupe step has no meaningful reverse — duplicates were
    bug artifacts, recreating them on rollback would just re-introduce
    the bug."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0016_backfill_tenant_channels'),
    ]

    operations = [
        # Step 1: merge any existing duplicates so step 2 can succeed.
        migrations.RunPython(_dedupe, _noop),
        # Step 2: prevent future duplicates at the DB layer.
        migrations.AddConstraint(
            model_name='chatchannel',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_dm', False)),
                fields=('owner', 'name'),
                name='uniq_chatchannel_owner_name_non_dm',
            ),
        ),
    ]
