# Generated by Django 4.2.30 on 2026-06-07 16:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderopsstate',
            name='line_item_costs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderopsstate',
            name='margin_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=6),
        ),
    ]
