# Generated by Django 4.2.30 on 2026-06-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_add_shopify_refresh_token'),
        ('sourcing_ops', '0002_orderopsstate_line_item_costs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossTenantSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=120, unique=True)),
                ('sample_name', models.CharField(blank=True, max_length=400)),
                ('sample_image', models.URLField(blank=True, max_length=600)),
                ('tenant_count', models.PositiveIntegerField(default=0)),
                ('listing_count', models.PositiveIntegerField(default=0)),
                ('avg_retail_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_retail_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_retail_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('has_supplier', models.BooleanField(default=False)),
                ('supplier_count', models.PositiveIntegerField(default=0)),
                ('avg_supplier_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-tenant_count', '-listing_count'],
                'indexes': [models.Index(fields=['-tenant_count'], name='sourcing_op_tenant__095a31_idx'), models.Index(fields=['has_supplier'], name='sourcing_op_has_sup_b30e5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('product_name', models.CharField(max_length=400)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('variant_count', models.PositiveIntegerField(default=0)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_cache', to='stores.store')),
            ],
            options={
                'ordering': ['-cached_at'],
                'indexes': [models.Index(fields=['sku'], name='sourcing_op_sku_4ef5a8_idx'), models.Index(fields=['store', 'sku'], name='sourcing_op_store_i_21436b_idx'), models.Index(fields=['is_active', '-cached_at'], name='sourcing_op_is_acti_e11d94_idx')],
                'unique_together': {('store', 'external_id')},
            },
        ),
    ]
