# Generated by Django 4.2.30 on 2026-06-08 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcing_ops', '0003_crosstenantsku_tenantproductcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsteammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio shown to tenants on chat header'),
        ),
        migrations.AddField(
            model_name='opsteammember',
            name='customer_facing',
            field=models.BooleanField(default=True, help_text='Can be auto-assigned as a dedicated manager'),
        ),
        migrations.AddField(
            model_name='opsteammember',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Headshot URL — replaces avatar emoji on tenant chat', max_length=600),
        ),
        migrations.AddField(
            model_name='opsteammember',
            name='signature',
            field=models.CharField(blank=True, help_text='Short signature line shown after messages', max_length=160),
        ),
        migrations.AddField(
            model_name='opsteammember',
            name='specialties_text',
            field=models.CharField(blank=True, help_text="Comma-separated specialties: 'Apparel, Beauty, Home'", max_length=255),
        ),
        migrations.AddField(
            model_name='opsteammember',
            name='typical_reply_min',
            field=models.PositiveSmallIntegerField(default=5, help_text='Typical reply time in minutes (shown to tenant)'),
        ),
        migrations.CreateModel(
            name='TenantManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_via', models.CharField(choices=[('auto_round_robin', 'Auto-assigned (load balanced)'), ('manual_ops', 'Manually assigned by ops'), ('tenant_request', 'Tenant requested specific manager'), ('migrated', 'Migrated from previous manager')], default='auto_round_robin', max_length=20)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('reassignment_reason', models.CharField(blank=True, max_length=255)),
                ('welcome_message_sent', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dedicated_tenants', to='sourcing_ops.opsteammember')),
                ('previous_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_tenants', to='sourcing_ops.opsteammember')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_manager_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['manager', '-assigned_at'], name='sourcing_op_manager_8514a5_idx')],
            },
        ),
    ]
