# Generated by Django 4.2.30 on 2026-06-12 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcing_ops', '0004_opsteammember_bio_opsteammember_customer_facing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(help_text='URL-safe id used in invite links', max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', help_text='Used for workspace chips in the superadmin UI', max_length=20)),
                ('emoji', models.CharField(default='🛠️', max_length=4)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to hide from invite lists + revoke member access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_workspaces_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='opsteammember',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='If set, this ops user only sees tenants assigned to that workspace. NULL = global ops user (sees everything).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='sourcing_ops.opsworkspace'),
        ),
        migrations.CreateModel(
            name='OpsWorkspaceTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, help_text='Optional reason / context for the assignment', max_length=255)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_tenant_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ops_workspace_assignment', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_assignments', to='sourcing_ops.opsworkspace')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['workspace', 'tenant'], name='sourcing_op_workspa_7967d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, help_text='Display name shown in the welcome email', max_length=120)),
                ('title', models.CharField(blank=True, help_text='Job title — copied to OpsTeamMember on accept', max_length=120)),
                ('is_manager', models.BooleanField(default=False, help_text='Promote the new member to workspace manager on accept')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text="Hard expiry — past this the link 404s even if still 'pending'.")),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='Updated whenever the invite email is (re-)sent', null=True)),
                ('send_count', models.PositiveIntegerField(default=0)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_invitations_revoked', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_invitations', to='sourcing_ops.opsrole')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='sourcing_ops.opsworkspace')),
            ],
            options={
                'ordering': ['-invited_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='sourcing_op_workspa_aacfbc_idx'), models.Index(fields=['email', 'status'], name='sourcing_op_email_3553b0_idx')],
            },
        ),
    ]
