# Generated by Django 4.2.30 on 2026-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing_ops', '0005_opsworkspace_opsteammember_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsactivity',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('assigned', 'Order assigned'), ('supplier', 'Supplier linked'), ('quote_sent', 'Quote sent'), ('paid', 'Order paid'), ('po_sent', 'PO sent to supplier'), ('production', 'Production update'), ('qc', 'QC inspection'), ('shipped', 'Shipment dispatched'), ('delivered', 'Order delivered'), ('delay', 'Delay reported'), ('issue', 'Issue raised'), ('cancelled', 'Order cancelled'), ('system', 'System event'), ('tenant_delete', 'Tenant removed from queue'), ('tenant_restore', 'Tenant restored to queue')], max_length=20),
        ),
    ]
