# Generated by Django 4.2.30 on 2026-05-28 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rma.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_shopifygdprrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_store_user_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('token', models.CharField(db_index=True, default=rma.models._new_token, max_length=64, unique=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_transit', 'In Transit'), ('received', 'Received'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('defective', 'Defective / Not working'), ('wrong_size', 'Wrong size'), ('damaged', 'Damaged in transit'), ('not_described', 'Not as described'), ('changed_mind', 'Changed my mind'), ('wrong_item', 'Received wrong item')], default='', max_length=30)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reject_note', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_currency', models.CharField(default='usd', max_length=10)),
                ('refund_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('restocking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_refund_id', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_charge_id', models.CharField(blank=True, default='', max_length=120)),
                ('refund_notes', models.TextField(blank=True, default='')),
                ('return_label_url', models.URLField(blank=True, default='')),
                ('return_tracking_no', models.CharField(blank=True, default='', max_length=120)),
                ('return_carrier', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmas_approved', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rmas', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmas', to='stores.store')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RMASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_window_days', models.PositiveIntegerField(default=30)),
                ('restocking_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shipping_policy', models.CharField(choices=[('free', 'Free for customer (you pay)'), ('customer_pays', 'Customer pays return shipping'), ('free_defects', 'Free for defects only')], default='free', max_length=20)),
                ('policy_text', models.TextField(blank=True, default='We accept returns within 30 days of delivery for any unused items in original packaging. Defective items receive a full refund including original shipping. Custom or final-sale items are not eligible.')),
                ('return_address_line1', models.CharField(blank=True, default='', max_length=200)),
                ('return_address_line2', models.CharField(blank=True, default='', max_length=200)),
                ('return_city', models.CharField(blank=True, default='', max_length=100)),
                ('return_state', models.CharField(blank=True, default='', max_length=100)),
                ('return_postcode', models.CharField(blank=True, default='', max_length=20)),
                ('return_country', models.CharField(blank=True, default='US', max_length=100)),
                ('auto_approve_defects_under', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('auto_approve_vip', models.BooleanField(default=True)),
                ('auto_flag_suspicious', models.BooleanField(default=True)),
                ('auto_generate_label', models.BooleanField(default=True)),
                ('enabled_reasons', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rma_settings', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='RMAPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='rma_photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rma.rma')),
            ],
        ),
        migrations.CreateModel(
            name='RMAMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('customer', 'From Customer'), ('tenant', 'From Tenant'), ('internal', 'Internal Note')], default='tenant', max_length=20)),
                ('body', models.TextField()),
                ('sender_name', models.CharField(blank=True, default='', max_length=120)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rma.rma')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RMAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=120)),
                ('variant_label', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image_url', models.URLField(blank=True, default='')),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rma.rma')),
            ],
        ),
        migrations.CreateModel(
            name='RMAEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('label_generated', 'Label Generated'), ('in_transit', 'In Transit'), ('received', 'Received'), ('refunded', 'Refunded'), ('message_sent', 'Message Sent'), ('note_added', 'Internal Note'), ('status_change', 'Status Change')], max_length=30)),
                ('actor_label', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rma.rma')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rma',
            index=models.Index(fields=['store', 'status'], name='rma_rma_store_i_54822b_idx'),
        ),
        migrations.AddIndex(
            model_name='rma',
            index=models.Index(fields=['store', 'submitted_at'], name='rma_rma_store_i_7f03ff_idx'),
        ),
    ]
