# Generated by Django 4.2.30 on 2026-05-28 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rma',
            name='customer_tracking_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rma',
            name='customer_tracking_company',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='rma',
            name='customer_tracking_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='rma',
            name='customer_tracking_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rma',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rma',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmas_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rma',
            name='source_email_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='rmasettings',
            name='auto_email_body',
            field=models.TextField(blank=True, default="Hi {{customer_name}},\n\nThanks for reaching out — we're sorry to hear about the issue. To start your return, please open this short form and submit the details:\n\n{{return_link}}\n\nYou'll get live status updates on the same link and can chat with us directly there.\n\n— {{store_name}} Support"),
        ),
        migrations.AddField(
            model_name='rmasettings',
            name='auto_email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rmasettings',
            name='auto_email_subject',
            field=models.CharField(blank=True, default='Re: {{subject}} — Start your return', max_length=255),
        ),
        migrations.AlterField(
            model_name='rma',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('tracking_submitted', 'Tracking Submitted'), ('in_transit', 'In Transit'), ('received', 'Received'), ('refunded', 'Refunded'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rmaevent',
            name='event_type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('label_generated', 'Label Generated'), ('tracking_submitted', 'Customer Submitted Tracking'), ('in_transit', 'In Transit'), ('received', 'Received'), ('refunded', 'Refunded'), ('resolved', 'Resolved'), ('message_sent', 'Message Sent'), ('note_added', 'Internal Note'), ('status_change', 'Status Change')], max_length=30),
        ),
    ]
