# Generated by Django 4.2.30 on 2026-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0002_rma_customer_tracking_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmasettings',
            name='dismissed_email_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
