# Generated by Django 4.2.30 on 2026-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0003_rmasettings_dismissed_email_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmasettings',
            name='auto_email_body',
            field=models.TextField(blank=True, default='<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:0;background:#f6f9fc;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}a{color:inherit}</style></head><body style="background:#f6f9fc;margin:0;padding:48px 16px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;background:#ffffff;border-radius:16px;border:1px solid #e2e8f0;overflow:hidden;box-shadow:0 6px 20px -10px rgba(15,23,42,.18);"><tr><td style="background:linear-gradient(135deg,#3b82f6,#6366f1);padding:6px 0;line-height:0;font-size:0;">&nbsp;</td></tr><tr><td style="padding:36px 44px 16px;text-align:center;"><div style="font-size:11px;font-weight:800;color:#3730a3;background:#eef2ff;border-radius:20px;display:inline-block;padding:5px 14px;letter-spacing:.5px;margin-bottom:18px;text-transform:uppercase;">📦 Return Request</div><h1 style="margin:0;font-size:24px;font-weight:800;color:#0f172a;line-height:1.3;letter-spacing:-.3px;">Let\'s get your return started</h1></td></tr><tr><td style="padding:8px 44px 0;"><p style="margin:0 0 16px;font-size:15px;color:#475569;line-height:1.7;">Hi <strong style="color:#0f172a;">{{customer_name}}</strong>,</p><p style="margin:0 0 22px;font-size:15px;color:#475569;line-height:1.7;">Thanks for reaching out — we\'re sorry to hear about the issue. To start your return, click the button below and submit the details. The whole thing takes about a minute.</p></td></tr><tr><td align="center" style="padding:0 44px 24px;"><table cellpadding="0" cellspacing="0"><tr><td style="background:linear-gradient(135deg,#3b82f6,#6366f1);border-radius:11px;box-shadow:0 4px 14px rgba(59,130,246,.35);"><a href="{{return_link}}" style="display:block;padding:15px 36px;font-size:15px;font-weight:800;color:#ffffff;text-decoration:none;letter-spacing:.2px;">Start my return →</a></td></tr></table></td></tr><tr><td style="padding:0 44px 28px;"><div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px 18px;"><p style="margin:0 0 6px;font-size:11px;font-weight:700;color:#64748b;text-transform:uppercase;letter-spacing:.5px;">Or copy this link</p><p style="margin:0;font-size:12.5px;color:#3b82f6;word-break:break-all;">{{return_link}}</p></div></td></tr><tr><td style="padding:0 44px 32px;"><div style="border-top:1px solid #eef2f7;padding-top:18px;"><p style="margin:0 0 10px;font-size:13px;font-weight:700;color:#0f172a;">What happens next</p><p style="margin:0;font-size:13px;color:#64748b;line-height:1.7;">You\'ll get live status updates on the same link as we review, approve, and process your return. You can also chat with us directly there — no email back-and-forth.</p></div></td></tr><tr><td style="background:#f8fafc;padding:18px 44px;text-align:center;border-top:1px solid #eef2f7;"><p style="margin:0;font-size:12px;color:#94a3b8;">— {{store_name}} Support</p></td></tr></table></td></tr></table></body></html>'),
        ),
    ]
