# Generated by Django 4.2.30 on 2026-05-20 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0006_add_user_ip_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPGeoCache',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('timezone_str', models.CharField(blank=True, max_length=64)),
                ('is_bot', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('timezone_str', models.CharField(blank=True, max_length=64)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, default='GET', max_length=10)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os_name', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'country_code'], name='superadmin__created_f494b9_idx'), models.Index(fields=['created_at', 'is_bot'], name='superadmin__created_57431a_idx'), models.Index(fields=['ip_address', 'created_at'], name='superadmin__ip_addr_e40938_idx')],
            },
        ),
    ]
