# Generated by Django 4.2.30 on 2026-05-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_ipgeocache_visitlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('stripe_mode', models.CharField(choices=[('test', 'Test mode'), ('live', 'Live mode')], default='test', max_length=10)),
                ('stripe_publishable_key', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_last_test_ok', models.BooleanField(default=False)),
                ('stripe_last_test_message', models.TextField(blank=True, default='')),
                ('stripe_account_label', models.CharField(blank=True, default='', max_length=200)),
                ('paypal_enabled', models.BooleanField(default=False)),
                ('paypal_mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
                ('paypal_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('paypal_client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('paypal_last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('paypal_last_test_ok', models.BooleanField(default=False)),
                ('paypal_last_test_message', models.TextField(blank=True, default='')),
                ('paypal_account_label', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform payment settings',
                'verbose_name_plural': 'Platform payment settings',
            },
        ),
    ]
