# Generated by Django 4.2.30 on 2026-05-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_platformpaymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpaymentsettings',
            name='paypal_merchant_email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
