# Generated by Django 4.2.30 on 2026-04-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_password_plain_vendor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='VendorPermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=255)),
                ('changes', models.JSONField(default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_logs', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
