# Generated by Django 4.2.30 on 2026-05-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('vendors', '0004_vendor_permissions_vendorpermissionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreVendorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='stores.store')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_assignments', to='vendors.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'store')},
            },
        ),
    ]
