# Generated by Django 4.2.30 on 2026-05-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('vendors', '0005_add_store_vendor_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingQueueSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_queue_setting', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTrackingAutoApprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_auto_approvals', to='stores.store')),
            ],
            options={
                'unique_together': {('product_id', 'store')},
            },
        ),
    ]
