# Generated by Django 4.2.30 on 2026-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_tracking_queue_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortrackingsubmission',
            name='is_auto_approved',
            field=models.BooleanField(default=False),
        ),
    ]
