# Generated by Django 4.2.30 on 2026-05-30 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0009_vendorpasswordresetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('auto_eligible', models.BooleanField(default=False)),
                ('requires_notes', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(blank=True, help_text='Future-proofing for variant-level quoting (v1: always null)', max_length=100, null=True)),
                ('currency', models.CharField(default='USD', help_text="Tenant's currency; v1 doesn't convert", max_length=8)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active (Locked)'), ('superseded', 'Superseded'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_pending', models.BooleanField(default=False, help_text="True if there's an open change request on this quote — UI badge")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='vendors.productvendorassignment')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vendor_7d', 'Vendor 7-day reminder'), ('tenant_14d', 'Tenant 14-day escalation')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='vendors.productvendorassignment')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('product_cost', 'Product Cost'), ('default_shipping', 'Default Shipping'), ('country_shipping', 'Country Shipping'), ('country_added', 'Country Added'), ('country_removed', 'Country Removed')], max_length=30)),
                ('country_code', models.CharField(blank=True, default='', help_text='Only for country_* change types', max_length=3)),
                ('old_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delta_abs', models.DecimalField(decimal_places=2, help_text='new_value - old_value', max_digits=10)),
                ('delta_pct', models.DecimalField(decimal_places=2, help_text='((new - old) / old) * 100; 0 if old=0', max_digits=10)),
                ('reason_key', models.CharField(help_text='FK-like to ReasonConfig.key', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('auto_approved', 'Auto-Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('auto_decision', models.BooleanField(default=False, help_text='True if status was decided by automation, not human')),
                ('automation_reason', models.CharField(blank=True, default='', help_text="Audit: why automation approved/escalated, e.g. 'cost_decrease', 'over_threshold_pct', 'reason_not_auto_eligible'", max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='vendors.vendorquote')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorTrustSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_mode', models.BooleanField(default=False)),
                ('threshold_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('threshold_abs', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_trust_settings', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_settings', to='vendors.vendor')),
            ],
            options={
                'unique_together': {('tenant', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='VendorShippingOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=3)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Review')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='vendors.vendorquote')),
            ],
            options={
                'indexes': [models.Index(fields=['quote', 'country_code'], name='vendors_ven_quote_i_bb3bd2_idx')],
                'unique_together': {('quote', 'country_code')},
            },
        ),
        migrations.AddIndex(
            model_name='vendorquote',
            index=models.Index(fields=['assignment', 'status'], name='vendors_ven_assignm_dce0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorquote',
            index=models.Index(fields=['status', '-submitted_at'], name='vendors_ven_status_bce472_idx'),
        ),
        migrations.AddIndex(
            model_name='quotereminderlog',
            index=models.Index(fields=['assignment', 'kind'], name='vendors_quo_assignm_e6912f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotereminderlog',
            unique_together={('assignment', 'kind')},
        ),
        migrations.AddIndex(
            model_name='quotechangerequest',
            index=models.Index(fields=['quote', 'status', '-submitted_at'], name='vendors_quo_quote_i_753142_idx'),
        ),
        migrations.AddIndex(
            model_name='quotechangerequest',
            index=models.Index(fields=['status', '-submitted_at'], name='vendors_quo_status_5d04df_idx'),
        ),
    ]
