# Generated by Django 4.2.30 on 2026-05-30
#
# Seed ReasonConfig rows for the Vendor Pricing & Approval System (v1).
# Idempotent — uses update_or_create on key.

from django.db import migrations


SEED_REASONS = [
    # key,                 label,                          auto_eligible, requires_notes, sort_order
    ("currency_fluctuation", "Currency fluctuation",          True,  False, 10),
    ("carrier_hike",         "Carrier rate hike",             True,  False, 20),
    ("country_tax_change",   "Country tax / duty change",     True,  False, 30),
    ("supplier_cost",        "Supplier cost changed",         False, False, 40),
    ("quality_sourcing",     "Quality / sourcing change",     False, False, 50),
    ("other",                "Other",                         False, True,  99),
]


def seed_reasons(apps, schema_editor):
    ReasonConfig = apps.get_model("vendors", "ReasonConfig")
    for key, label, auto_eligible, requires_notes, sort_order in SEED_REASONS:
        ReasonConfig.objects.update_or_create(
            key=key,
            defaults={
                "label": label,
                "auto_eligible": auto_eligible,
                "requires_notes": requires_notes,
                "sort_order": sort_order,
            },
        )


def unseed_reasons(apps, schema_editor):
    ReasonConfig = apps.get_model("vendors", "ReasonConfig")
    keys = [r[0] for r in SEED_REASONS]
    ReasonConfig.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0010_vendor_pricing"),
    ]

    operations = [
        migrations.RunPython(seed_reasons, reverse_code=unseed_reasons),
    ]
