# Generated by Django 4.2.30 on 2026-05-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_user_nullable'),
        ('vendors', '0011_seed_reason_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='assigned_store',
            field=models.ForeignKey(blank=True, help_text='Initial store assignment — optional. A vendor can later be linked to multiple stores via StoreVendorAssignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='vendorinvitation',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invitations', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='vendorpasswordresetrequest',
            name='requested_ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='vendorpasswordresetrequest',
            name='resolved_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorpasswordresetrequest',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
