# Generated by Django 4.2.30 on 2026-06-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='refresh_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
