# Generated by Django 4.2.30 on 2026-04-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('orders', '0002_order_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='order',
            name='assignment_type',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
