# Generated by Django 4.2.30 on 2026-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_assigned_vendor_order_assignment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('tracking_submitted', 'Tracking Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='unassigned', max_length=50),
        ),
    ]
