# Generated by Django 4.2.30 on 2026-04-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_vendor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('received', 'Order Received'), ('assigned', 'Order Assigned'), ('vendor_assigned', 'Vendor Assigned'), ('tracking_submitted', 'Tracking Submitted'), ('tracking_approved', 'Tracking Approved'), ('tracking_rejected', 'Tracking Rejected'), ('tracking_added', 'Tracking Added'), ('note', 'Note')], max_length=50)),
                ('description', models.TextField()),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
