# Generated by Django 4.2.30 on 2026-05-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
