# Generated by Django 4.2.30 on 2026-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_tracking_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='live_tracking_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
