# Generated by Django 4.2.30 on 2026-05-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyGdprRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('data_request', 'Customer Data Request'), ('customers_redact', 'Customer Redact'), ('shop_redact', 'Shop Redact')], db_index=True, max_length=32)),
                ('shop_domain', models.CharField(db_index=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_type', '-created_at'], name='orders_shop_request_96316c_idx'), models.Index(fields=['shop_domain', '-created_at'], name='orders_shop_shop_do_2fb03c_idx')],
            },
        ),
    ]
