# Generated by Django 4.2.30 on 2026-06-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing_partners', '0002_lockedprice_vendororder_workspaceactivity_and_more'),
        ('orders', '0009_shopifygdprrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_override',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_lead_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_locked_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_orders', to='sourcing_partners.lockedprice'),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_partner',
            field=models.ForeignKey(blank=True, help_text='Internal routing — never surfaced to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_orders', to='sourcing_partners.sourcingpartner'),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_status',
            field=models.CharField(choices=[('pending_source', 'Pending Source'), ('pending_payment', 'Pending Payment'), ('processing', 'Processing'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('cancel', 'Cancelled')], db_index=True, default='pending_source', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Drop Sigma's quoted total for the tenant — wallet charge amount.", max_digits=10, null=True),
        ),
    ]
