# Generated by Django 4.2.30 on 2026-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_shipping_override_order_sourcing_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sourcing_product_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product cost portion of the sourcing quote.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sourcing_shipping_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shipping cost portion of the sourcing quote.', max_digits=10, null=True),
        ),
    ]
