# Portal default templates — permanent portal defaults, independent of any store

PORTAL_DEFAULT_TEMPLATES = [
    {
        'name': 'Order Cancelled — Amazon Style',
        'category': 'cancelled',
        'status': 'active',
        'subject': 'Cancellation confirmation for order #{{order_id}}',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f0f2f2;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f0f2f2;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#232F3E;padding:20px 40px;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:20px;font-weight:700;color:#FF9900;">{{store_name}}</td>\n  <td align="right" style="font-size:13px;color:#aab7c4;">Order Cancelled</td>\n</tr></table>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<p style="margin:0 0 16px;font-size:16px;color:#111;font-weight:600;">Hello {{customer_name}},</p>\n<p style="margin:0 0 24px;font-size:14px;color:#333;">Your order <strong>#{{order_id}}</strong> has been cancelled.</p>\n\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;margin-bottom:24px;background:#fff8f8;">\n  <p style="margin:0 0 8px;font-size:13px;font-weight:600;color:#111;">Cancellation Details</p>\n  <table width="100%" cellpadding="0" cellspacing="0">\n    <tr>\n      <td style="font-size:13px;color:#767676;padding-top:6px;">Order Number</td>\n      <td align="right" style="font-size:13px;color:#111;padding-top:6px;">#{{order_id}}</td>\n    </tr>\n    <tr>\n      <td style="font-size:13px;color:#767676;padding-top:6px;">Date</td>\n      <td align="right" style="font-size:13px;color:#111;padding-top:6px;">{{order_date}}</td>\n    </tr>\n    <tr>\n      <td style="font-size:13px;color:#767676;padding-top:6px;">Reason</td>\n      <td align="right" style="font-size:13px;color:#111;padding-top:6px;">{{cancel_reason}}</td>\n    </tr>\n  </table>\n</div>\n\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;margin-bottom:24px;">\n  <p style="margin:0 0 14px;font-size:14px;font-weight:600;color:#111;">Cancelled Items</p>\n  {{order_items}}\n</div>\n\n<p style="font-size:13px;color:#555;">If a payment was made, your refund will be processed within 3–5 business days.</p>\n</td></tr>\n<tr><td style="background:#232F3E;padding:16px 40px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#aab7c4;">© {{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'order_cancelled',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Order Cancelled — Luxury Style',
        'category': 'cancelled',
        'status': 'active',
        'subject': 'Order Cancellation Notice — {{store_name}}',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#ede8df;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#ede8df;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#f9f5ee;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#f9f5ee;padding:40px 48px 28px;text-align:center;border-bottom:1px solid #e8ddd0;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;">Order Notice</p>\n<h1 style="margin:0;font-size:28px;font-weight:400;color:#2c1810;font-family:Georgia,serif;letter-spacing:1px;">{{store_name}}</h1>\n</td></tr>\n<tr><td style="background:#f9f5ee;padding:36px 48px;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;text-align:center;">ORDER CANCELLED</p>\n<h2 style="margin:0 0 24px;font-size:22px;font-weight:400;color:#2c1810;font-family:Georgia,serif;text-align:center;">Dear {{customer_name}},</h2>\n<p style="font-size:15px;color:#5c3d2e;line-height:1.7;margin:0 0 28px;text-align:center;">We regret to inform you that your order has been cancelled.<br>We sincerely apologize for any inconvenience.</p>\n\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">\n<tr>\n  <td width="50%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Order Reference</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#2c1810;font-family:Georgia,serif;">#{{order_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="46%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Date</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#2c1810;font-family:Georgia,serif;">{{order_date}}</p>\n  </td>\n</tr>\n</table>\n\n<div style="border:1px solid #ddd2be;border-radius:4px;padding:16px 20px;margin-bottom:24px;background:#fdf9f3;">\n  <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Reason</p>\n  <p style="margin:0;font-size:14px;color:#2c1810;font-family:Georgia,serif;">{{cancel_reason}}</p>\n</div>\n\n<div style="border-top:1px solid #e8ddd0;padding-top:20px;">\n  <p style="margin:0 0 12px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Cancelled Items</p>\n  {{order_items}}\n</div>\n</td></tr>\n<tr><td style="background:#3d2314;padding:24px 48px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#c4a882;letter-spacing:0.5px;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'order_cancelled',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Order Cancelled — Shopify',
        'category': 'cancelled',
        'status': 'active',
        'subject': 'Your order #{{order_id}} has been cancelled',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f4f4f4;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f4f4f4;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#ffffff;padding:32px 40px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:18px;font-weight:700;color:#1a1a1a;">{{store_name}}</td>\n  <td align="right" style="font-size:14px;color:#6b7280;font-weight:600;">Order Cancelled</td>\n</tr></table>\n<div style="height:3px;background:#ef4444;border-radius:2px;margin-top:12px;"></div>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<div style="text-align:center;margin-bottom:28px;">\n  <div style="width:56px;height:56px;background:#fee2e2;border-radius:50%;margin:0 auto 16px;display:flex;align-items:center;justify-content:center;">\n    <span style="font-size:26px;">✖</span>\n  </div>\n  <h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1a1a1a;">Your order has been cancelled</h1>\n  <p style="margin:0;font-size:15px;color:#6b7280;">Hi {{customer_name}}, your order #{{order_id}} has been cancelled.</p>\n</div>\n\n<!-- Reason box -->\n<div style="background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:16px 20px;margin-bottom:24px;">\n  <p style="margin:0 0 4px;font-size:12px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Cancellation Reason</p>\n  <p style="margin:0;font-size:14px;color:#1a1a1a;">{{cancel_reason}}</p>\n</div>\n\n<!-- Order info bar -->\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">\n<tr>\n  <td width="48%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Order Number</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#1a1a1a;">#{{order_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="48%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Date</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#1a1a1a;">{{order_date}}</p>\n  </td>\n</tr>\n</table>\n\n<p style="font-size:14px;color:#6b7280;margin:0 0 20px;">If a payment was made, a refund will be issued within 3–5 business days. If you have questions, please reply to this email.</p>\n\n<p style="font-size:13px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 12px;">Cancelled Items</p>\n{{order_items}}\n</td></tr>\n<tr><td style="background:#f9fafb;padding:20px 40px;text-align:center;border-top:1px solid #e5e7eb;">\n<p style="margin:0;font-size:12px;color:#9ca3af;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'order_cancelled',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': True,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Dispute Acknowledgement — Amazon Style',
        'category': 'dispute',
        'status': 'active',
        'subject': 'Dispute case opened for order #{{order_id}} — {{store_name}}',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f0f2f2;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f0f2f2;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#232F3E;padding:20px 40px;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:20px;font-weight:700;color:#FF9900;">{{store_name}}</td>\n  <td align="right" style="font-size:13px;color:#aab7c4;">Dispute Case Opened</td>\n</tr></table>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<p style="margin:0 0 16px;font-size:16px;color:#111;font-weight:600;">Hello {{customer_name}},</p>\n<p style="margin:0 0 24px;font-size:14px;color:#333;">We have received your dispute for order <strong>#{{order_id}}</strong> and a case has been opened.</p>\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;margin-bottom:24px;background:#f7f7f7;">\n  <p style="margin:0 0 12px;font-size:14px;font-weight:600;color:#111;">Case Information</p>\n  <table width="100%" cellpadding="0" cellspacing="0;">\n    <tr>\n      <td style="font-size:13px;color:#767676;">Case ID</td>\n      <td align="right" style="font-size:13px;font-weight:600;color:#111;">{{dispute_id}}</td>\n    </tr>\n    <tr>\n      <td style="font-size:13px;color:#767676;padding-top:8px;">Order Number</td>\n      <td align="right" style="font-size:13px;font-weight:600;color:#111;padding-top:8px;">#{{order_id}}</td>\n    </tr>\n    <tr>\n      <td style="font-size:13px;color:#767676;padding-top:8px;">Reason</td>\n      <td align="right" style="font-size:13px;color:#111;padding-top:8px;">{{dispute_reason}}</td>\n    </tr>\n    <tr>\n      <td style="font-size:13px;color:#767676;padding-top:8px;">Status</td>\n      <td align="right" style="font-size:13px;color:#e47911;font-weight:600;padding-top:8px;">Under Review</td>\n    </tr>\n  </table>\n</div>\n<p style="font-size:13px;color:#555;margin:0 0 20px;">Our team will respond within 2–3 business days. No further action is required from you.</p>\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;">\n  <p style="margin:0 0 14px;font-size:14px;font-weight:600;color:#111;">Related Order Items</p>\n  {{order_items}}\n</div>\n</td></tr>\n<tr><td style="background:#232F3E;padding:16px 40px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#aab7c4;">© {{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'manual',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Dispute Acknowledgement — Luxury Style',
        'category': 'dispute',
        'status': 'active',
        'subject': 'Dispute Notice — Case {{dispute_id}} | {{store_name}}',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#ede8df;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#ede8df;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#f9f5ee;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#f9f5ee;padding:40px 48px 28px;text-align:center;border-bottom:1px solid #e8ddd0;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;">Dispute Notice</p>\n<h1 style="margin:0;font-size:28px;font-weight:400;color:#2c1810;font-family:Georgia,serif;letter-spacing:1px;">{{store_name}}</h1>\n</td></tr>\n<tr><td style="background:#f9f5ee;padding:36px 48px;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;text-align:center;">YOUR DISPUTE IS UNDER REVIEW</p>\n<h2 style="margin:0 0 24px;font-size:22px;font-weight:400;color:#2c1810;font-family:Georgia,serif;text-align:center;">Dear {{customer_name}},</h2>\n<p style="font-size:15px;color:#5c3d2e;line-height:1.7;margin:0 0 28px;text-align:center;">We have received your dispute and wish to assure you that<br>your concerns are being handled with the utmost care.</p>\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">\n<tr>\n  <td width="50%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Case Reference</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#2c1810;font-family:Georgia,serif;">{{dispute_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="46%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Order Reference</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#2c1810;font-family:Georgia,serif;">#{{order_id}}</p>\n  </td>\n</tr>\n</table>\n<div style="border:1px solid #ddd2be;border-radius:4px;padding:16px 20px;margin-bottom:24px;background:#fdf9f3;">\n  <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Nature of Dispute</p>\n  <p style="margin:0;font-size:14px;color:#2c1810;font-family:Georgia,serif;">{{dispute_reason}}</p>\n</div>\n<p style="font-size:14px;color:#5c3d2e;line-height:1.7;margin:0 0 24px;">A member of our team will be in touch within 2–3 business days. No further action is required from you at this time.</p>\n<div style="border-top:1px solid #e8ddd0;padding-top:20px;">\n  <p style="margin:0 0 12px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Related Order</p>\n  {{order_items}}\n</div>\n</td></tr>\n<tr><td style="background:#3d2314;padding:24px 48px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#c4a882;letter-spacing:0.5px;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'manual',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Dispute Acknowledgement — Shopify',
        'category': 'dispute',
        'status': 'active',
        'subject': 'We have received your dispute for order #{{order_id}}',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f4f4f4;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f4f4f4;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#ffffff;padding:32px 40px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:18px;font-weight:700;color:#1a1a1a;">{{store_name}}</td>\n  <td align="right" style="font-size:14px;color:#6b7280;font-weight:600;">Dispute Received</td>\n</tr></table>\n<div style="height:3px;background:#008060;border-radius:2px;margin-top:12px;"></div>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<div style="text-align:center;margin-bottom:28px;">\n  <div style="width:56px;height:56px;background:#fef3c7;border-radius:50%;margin:0 auto 16px;">\n    <span style="font-size:26px;line-height:56px;">🛡️</span>\n  </div>\n  <h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1a1a1a;">We\'ve received your dispute</h1>\n  <p style="margin:0;font-size:15px;color:#6b7280;">Hi {{customer_name}}, we take every concern seriously and are reviewing your case.</p>\n</div>\n<div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:20px 24px;margin-bottom:24px;">\n  <p style="margin:0 0 4px;font-size:12px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Dispute Details</p>\n  <p style="margin:0 0 10px;font-size:14px;color:#1a1a1a;">{{dispute_reason}}</p>\n  <table width="100%" cellpadding="0" cellspacing="0">\n    <tr>\n      <td style="font-size:13px;color:#6b7280;">Case ID</td>\n      <td align="right" style="font-size:13px;font-weight:600;color:#1a1a1a;">{{dispute_id}}</td>\n    </tr>\n    <tr>\n      <td style="font-size:13px;color:#6b7280;padding-top:6px;">Order</td>\n      <td align="right" style="font-size:13px;font-weight:600;color:#1a1a1a;padding-top:6px;">#{{order_id}}</td>\n    </tr>\n    <tr>\n      <td style="font-size:13px;color:#6b7280;padding-top:6px;">Status</td>\n      <td align="right" style="padding-top:6px;"><span style="display:inline-block;background:#d1fae5;color:#065f46;font-size:12px;font-weight:600;padding:3px 10px;border-radius:9999px;">Under Review</span></td>\n    </tr>\n  </table>\n</div>\n<p style="font-size:14px;color:#6b7280;margin:0 0 20px;">Our support team will review your case within <strong>2–3 business days</strong> and respond via email. You do not need to take any further action at this time.</p>\n<p style="font-size:13px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 12px;">Related Order</p>\n{{order_items}}\n</td></tr>\n<tr><td style="background:#f9fafb;padding:20px 40px;text-align:center;border-top:1px solid #e5e7eb;">\n<p style="margin:0;font-size:12px;color:#9ca3af;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'manual',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': True,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Payment Failed — Amazon Style',
        'category': 'failed',
        'status': 'active',
        'subject': 'Important: Payment issue with your {{store_name}} order',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f0f2f2;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f0f2f2;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#232F3E;padding:20px 40px;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:20px;font-weight:700;color:#FF9900;">{{store_name}}</td>\n  <td align="right" style="font-size:13px;color:#aab7c4;">Payment Issue</td>\n</tr></table>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<p style="margin:0 0 16px;font-size:16px;color:#111;font-weight:600;">Hello {{customer_name}},</p>\n<p style="margin:0 0 24px;font-size:14px;color:#333;">We were unable to process the payment for order <strong>#{{order_id}}</strong>. Please update your payment information to complete your purchase.</p>\n\n<div style="border:1px solid #fde68a;border-radius:4px;padding:16px 20px;margin-bottom:24px;background:#fffbeb;">\n  <p style="margin:0;font-size:13px;color:#92400e;">⚠️ Action Required: Your items are still reserved but will not be shipped until payment is confirmed.</p>\n</div>\n\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;margin-bottom:24px;background:#f7f7f7;">\n  <table width="100%" cellpadding="0" cellspacing="0">\n    <tr>\n      <td style="font-size:13px;color:#767676;">Order Number</td>\n      <td align="right" style="font-size:13px;font-weight:600;color:#111;">#{{order_id}}</td>\n    </tr>\n    <tr>\n      <td style="font-size:13px;color:#767676;padding-top:8px;">Amount Due</td>\n      <td align="right" style="font-size:16px;font-weight:700;color:#b12704;padding-top:8px;">{{order_total}}</td>\n    </tr>\n  </table>\n</div>\n\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">\n<tr><td><a href="#" style="display:inline-block;background:#FF9900;color:#111;font-size:14px;font-weight:700;text-decoration:none;padding:11px 28px;border-radius:4px;border:1px solid #e68a00;">Update Payment Method</a></td></tr>\n</table>\n\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;">\n  <p style="margin:0 0 14px;font-size:14px;font-weight:600;color:#111;">Items in Your Order</p>\n  {{order_items}}\n</div>\n</td></tr>\n<tr><td style="background:#232F3E;padding:16px 40px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#aab7c4;">© {{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'payment_failed',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Payment Failed — Luxury Style',
        'category': 'failed',
        'status': 'active',
        'subject': 'Payment Notice — Order #{{order_id}}',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#ede8df;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#ede8df;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#f9f5ee;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#f9f5ee;padding:40px 48px 28px;text-align:center;border-bottom:1px solid #e8ddd0;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;">Payment Notice</p>\n<h1 style="margin:0;font-size:28px;font-weight:400;color:#2c1810;font-family:Georgia,serif;letter-spacing:1px;">{{store_name}}</h1>\n</td></tr>\n<tr><td style="background:#f9f5ee;padding:36px 48px;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;text-align:center;">PAYMENT UNSUCCESSFUL</p>\n<h2 style="margin:0 0 24px;font-size:22px;font-weight:400;color:#2c1810;font-family:Georgia,serif;text-align:center;">Dear {{customer_name}},</h2>\n<p style="font-size:15px;color:#5c3d2e;line-height:1.7;margin:0 0 28px;text-align:center;">We were unable to process your payment for order #{{order_id}}.<br>Your items are being held and await your attention.</p>\n\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">\n<tr>\n  <td width="50%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Order Reference</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#2c1810;font-family:Georgia,serif;">#{{order_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="46%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Amount Due</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#b8622a;font-family:Georgia,serif;">{{order_total}}</p>\n  </td>\n</tr>\n</table>\n\n<div style="text-align:center;margin-bottom:24px;">\n  <a href="#" style="display:inline-block;background:#b8622a;color:#ffffff;font-size:13px;letter-spacing:1px;text-decoration:none;padding:11px 30px;border-radius:2px;text-transform:uppercase;">Update Payment Method</a>\n</div>\n\n<div style="border-top:1px solid #e8ddd0;padding-top:20px;">\n  <p style="margin:0 0 12px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Your Reserved Items</p>\n  {{order_items}}\n</div>\n</td></tr>\n<tr><td style="background:#3d2314;padding:24px 48px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#c4a882;letter-spacing:0.5px;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'payment_failed',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Payment Failed — Shopify',
        'category': 'failed',
        'status': 'active',
        'subject': 'Action required: Payment failed for order #{{order_id}}',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f4f4f4;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f4f4f4;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#ffffff;padding:32px 40px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:18px;font-weight:700;color:#1a1a1a;">{{store_name}}</td>\n  <td align="right" style="font-size:14px;color:#6b7280;font-weight:600;">Payment Failed</td>\n</tr></table>\n<div style="height:3px;background:#f59e0b;border-radius:2px;margin-top:12px;"></div>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<div style="text-align:center;margin-bottom:28px;">\n  <div style="width:56px;height:56px;background:#fef3c7;border-radius:50%;margin:0 auto 16px;display:flex;align-items:center;justify-content:center;">\n    <span style="font-size:26px;">⚠️</span>\n  </div>\n  <h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1a1a1a;">Payment was not successful</h1>\n  <p style="margin:0;font-size:15px;color:#6b7280;">Hi {{customer_name}}, we were unable to process your payment for order #{{order_id}}.</p>\n</div>\n\n<!-- Alert box -->\n<div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:16px 20px;margin-bottom:24px;">\n  <p style="margin:0;font-size:14px;color:#92400e;">Please update your payment information or try a different payment method to complete your order. Your items are still being held.</p>\n</div>\n\n<!-- Order info bar -->\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">\n<tr>\n  <td width="48%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Order Number</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#1a1a1a;">#{{order_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="48%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Amount Due</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#ef4444;">{{order_total}}</p>\n  </td>\n</tr>\n</table>\n\n<div style="text-align:center;margin-bottom:24px;">\n  <a href="#" style="display:inline-block;background:#008060;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:12px 32px;border-radius:6px;">Update Payment Method</a>\n</div>\n\n<p style="font-size:13px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 12px;">Your Order</p>\n{{order_items}}\n</td></tr>\n<tr><td style="background:#f9fafb;padding:20px 40px;text-align:center;border-top:1px solid #e5e7eb;">\n<p style="margin:0;font-size:12px;color:#9ca3af;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'payment_failed',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': True,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Follow-up — Amazon Style',
        'category': 'followup',
        'status': 'active',
        'subject': 'Tell us about your {{store_name}} experience',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f0f2f2;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f0f2f2;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#232F3E;padding:20px 40px;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:20px;font-weight:700;color:#FF9900;">{{store_name}}</td>\n  <td align="right" style="font-size:13px;color:#aab7c4;">Customer Feedback</td>\n</tr></table>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<p style="margin:0 0 16px;font-size:16px;color:#111;font-weight:600;">Hello {{customer_name}},</p>\n<p style="margin:0 0 24px;font-size:14px;color:#333;">Thank you for your recent purchase. We\'d love to hear how your experience was.</p>\n\n<div style="border:1px solid #ddd;border-radius:4px;padding:24px;margin-bottom:24px;text-align:center;background:#fffdf0;">\n  <p style="margin:0 0 8px;font-size:15px;font-weight:600;color:#111;">How would you rate your experience?</p>\n  <p style="margin:0 0 16px;font-size:28px;letter-spacing:6px;color:#FF9900;">★★★★★</p>\n  <a href="#" style="display:inline-block;background:#FF9900;color:#111;font-size:14px;font-weight:700;text-decoration:none;padding:10px 24px;border-radius:4px;border:1px solid #e68a00;">Write a Review</a>\n</div>\n\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;margin-bottom:24px;">\n  <p style="margin:0 0 6px;font-size:13px;color:#767676;">Order Reference: <strong style="color:#111;">#{{order_id}}</strong></p>\n  <p style="margin:0 0 14px;font-size:14px;font-weight:600;color:#111;">Your Order</p>\n  {{order_items}}\n</div>\n\n<table width="100%" cellpadding="0" cellspacing="0">\n<tr><td><a href="#" style="display:inline-block;background:#f7f7f7;color:#111;font-size:13px;font-weight:600;text-decoration:none;padding:10px 24px;border-radius:4px;border:1px solid #ddd;">Visit Our Store →</a></td></tr>\n</table>\n</td></tr>\n<tr><td style="background:#232F3E;padding:16px 40px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#aab7c4;">© {{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'no_activity_7d',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Follow-up — Luxury Style',
        'category': 'followup',
        'status': 'active',
        'subject': 'We value your experience — {{store_name}}',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#ede8df;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#ede8df;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#f9f5ee;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#f9f5ee;padding:40px 48px 28px;text-align:center;border-bottom:1px solid #e8ddd0;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;">Your Experience</p>\n<h1 style="margin:0;font-size:28px;font-weight:400;color:#2c1810;font-family:Georgia,serif;letter-spacing:1px;">{{store_name}}</h1>\n</td></tr>\n<tr><td style="background:#f9f5ee;padding:36px 48px;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;text-align:center;">WE VALUE YOUR OPINION</p>\n<h2 style="margin:0 0 24px;font-size:22px;font-weight:400;color:#2c1810;font-family:Georgia,serif;text-align:center;">Dear {{customer_name}},</h2>\n<p style="font-size:15px;color:#5c3d2e;line-height:1.7;margin:0 0 28px;text-align:center;">We trust your purchase has exceeded your expectations.<br>Your thoughts help us continue to refine our service.</p>\n\n<div style="text-align:center;margin-bottom:28px;">\n  <p style="margin:0 0 12px;font-size:24px;letter-spacing:8px;color:#b8622a;">★ ★ ★ ★ ★</p>\n  <a href="#" style="display:inline-block;background:#b8622a;color:#ffffff;font-size:13px;letter-spacing:1px;text-decoration:none;padding:11px 30px;border-radius:2px;text-transform:uppercase;">Share Your Experience</a>\n</div>\n\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">\n<tr>\n  <td width="50%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Order Reference</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#2c1810;font-family:Georgia,serif;">#{{order_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="46%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Order Date</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#2c1810;font-family:Georgia,serif;">{{order_date}}</p>\n  </td>\n</tr>\n</table>\n\n<div style="border-top:1px solid #e8ddd0;padding-top:20px;">\n  <p style="margin:0 0 12px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">YOUR PURCHASE</p>\n  {{order_items}}\n</div>\n</td></tr>\n<tr><td style="background:#3d2314;padding:24px 48px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#c4a882;letter-spacing:0.5px;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'no_activity_7d',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Follow-up — Shopify',
        'category': 'followup',
        'status': 'active',
        'subject': 'How did we do? Your feedback matters 🌟',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f4f4f4;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f4f4f4;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#ffffff;padding:32px 40px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:18px;font-weight:700;color:#1a1a1a;">{{store_name}}</td>\n  <td align="right" style="font-size:14px;color:#6b7280;font-weight:600;">We\'d Love Your Feedback</td>\n</tr></table>\n<div style="height:3px;background:#008060;border-radius:2px;margin-top:12px;"></div>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<div style="text-align:center;margin-bottom:28px;">\n  <div style="width:56px;height:56px;background:#d1fae5;border-radius:50%;margin:0 auto 16px;display:flex;align-items:center;justify-content:center;">\n    <span style="font-size:26px;">⭐</span>\n  </div>\n  <h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1a1a1a;">How did we do?</h1>\n  <p style="margin:0;font-size:15px;color:#6b7280;">Hi {{customer_name}}, we hope you\'re loving your recent purchase. We\'d appreciate your feedback!</p>\n</div>\n\n<!-- Star rating CTA -->\n<div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:24px;margin-bottom:24px;text-align:center;">\n  <p style="margin:0 0 16px;font-size:15px;color:#1a1a1a;font-weight:600;">Rate your experience</p>\n  <p style="margin:0 0 18px;font-size:28px;letter-spacing:6px;">★★★★★</p>\n  <a href="#" style="display:inline-block;background:#008060;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:11px 28px;border-radius:6px;">Leave a Review</a>\n</div>\n\n<!-- Order reference -->\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">\n<tr>\n  <td width="48%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Order</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#1a1a1a;">#{{order_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="48%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Date</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#1a1a1a;">{{order_date}}</p>\n  </td>\n</tr>\n</table>\n\n<p style="font-size:13px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 12px;">Your Purchase</p>\n{{order_items}}\n</td></tr>\n<tr><td style="background:#f9fafb;padding:20px 40px;text-align:center;border-top:1px solid #e5e7eb;">\n<p style="margin:0;font-size:12px;color:#9ca3af;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'no_activity_7d',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': True,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Order Confirmation — Amazon Style',
        'category': 'order',
        'status': 'active',
        'subject': 'Your order {{order_id}} has been placed',
        'preheader': "Thank you for shopping with us. Here's your order summary.",
        'body_html': '<div style="background:#f3f3f3;padding:20px 0;font-family:Arial,Helvetica,sans-serif;color:#0f1111;">\n<div style="max-width:580px;margin:0 auto;padding:0 16px;">\n\n  <!-- Dark Navy Header -->\n  <div style="background:#232f3e;padding:16px 24px;border-radius:4px 4px 0 0;">\n    <table width="100%" cellpadding="0" cellspacing="0"><tr>\n      <td style="font-size:18px;font-weight:700;color:#FF9900;">{{store_name}}</td>\n      <td align="right" style="font-size:13px;color:#aab7c4;">Order Confirmation</td>\n    </tr></table>\n  </div>\n\n  <!-- Info Bar -->\n  <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:16px;background:#f7f7f7;border:1px solid #ddd;border-top:none;">\n    <tr>\n      <td width="33%" style="text-align:center;padding:14px 8px;border-right:1px solid #ddd;">\n        <p style="margin:0 0 3px;font-size:11px;color:#767676;font-weight:700;">ORDER PLACED</p>\n        <p style="margin:0;font-size:13px;font-weight:600;color:#111;">{{order_date}}</p>\n      </td>\n      <td width="33%" style="text-align:center;padding:14px 8px;border-right:1px solid #ddd;">\n        <p style="margin:0 0 3px;font-size:11px;color:#767676;font-weight:700;">ORDER #</p>\n        <p style="margin:0;font-size:13px;font-weight:600;color:#111;">{{order_id}}</p>\n      </td>\n      <td width="33%" style="text-align:center;padding:14px 8px;">\n        <p style="margin:0 0 3px;font-size:11px;color:#767676;font-weight:700;">ORDER TOTAL</p>\n        <p style="margin:0;font-size:13px;font-weight:600;color:#111;">{{order_total}}</p>\n      </td>\n    </tr>\n  </table>\n\n  <p style="margin:0 0 16px;font-size:15px;color:#0f1111;">Hi <strong>{{customer_name}}</strong>, thank you for your order. We&#39;re preparing it now and will keep you updated.</p>\n\n  <!-- Items Ordered -->\n  <div style="border:1px solid #ddd;border-radius:3px;overflow:hidden;margin-bottom:20px;">\n    <div style="background:#f7f7f7;border-bottom:1px solid #ddd;padding:10px 18px;">\n      <p style="margin:0;font-size:13px;font-weight:700;color:#0f1111;">Items Ordered</p>\n    </div>\n    <div style="padding:0 18px;">\n    {{order_items}}\n    </div>\n  </div>\n\n    <!-- Order Summary -->\n    <div style="border:1px solid #ddd;border-radius:3px;overflow:hidden;margin-bottom:20px;">\n      <div style="background:#f7f7f7;border-bottom:1px solid #ddd;padding:10px 18px;">\n        <p style="margin:0;font-size:13px;font-weight:700;color:#0f1111;">Order Summary</p>\n      </div>\n      <table width="100%" cellpadding="0" cellspacing="0" style="padding:14px 18px;">\n        <tr>\n          <td style="padding:4px 0;font-size:13px;color:#565959;">Items:</td>\n          <td style="padding:4px 0;font-size:13px;color:#0f1111;text-align:right;">{{subtotal}}</td>\n        </tr>\n        <tr>\n          <td style="padding:4px 0;font-size:13px;color:#565959;">Shipping &amp; handling:</td>\n          <td style="padding:4px 0;font-size:13px;color:#0f1111;text-align:right;">{{shipping_amount}}</td>\n        </tr>\n        <tr>\n          <td style="padding:4px 0;font-size:13px;color:#565959;">Tax:</td>\n          <td style="padding:4px 0;font-size:13px;color:#0f1111;text-align:right;">{{tax_amount}}</td>\n        </tr>\n        <tr>\n          <td style="padding:10px 0 4px;font-size:15px;font-weight:700;color:#0f1111;border-top:1px solid #ddd;">Order Total:</td>\n          <td style="padding:10px 0 4px;font-size:15px;font-weight:700;color:#b12704;text-align:right;border-top:1px solid #ddd;">{{order_total}}</td>\n        </tr>\n        <tr>\n          <td colspan="2" style="padding:4px 0;font-size:12px;color:#565959;">\n            Payment: {{payment_method}} &nbsp;·&nbsp; <span style="color:#007600;font-weight:700;">{{payment_status}}</span>\n          </td>\n        </tr>\n      </table>\n    </div>\n\n    <!-- Shipping Address -->\n    <div style="border:1px solid #ddd;border-radius:3px;overflow:hidden;margin-bottom:24px;">\n      <div style="background:#f7f7f7;border-bottom:1px solid #ddd;padding:10px 18px;">\n        <p style="margin:0;font-size:13px;font-weight:700;color:#0f1111;">Shipping Address</p>\n      </div>\n      <div style="padding:14px 18px;">\n        <p style="margin:0;font-size:13px;color:#0f1111;font-weight:700;">{{customer_name}}</p>\n        <p style="margin:4px 0 0;font-size:13px;color:#565959;line-height:1.6;">{{shipping_full_address}}</p>\n      </div>\n    </div>\n\n    <!-- CTA -->\n    <div style="text-align:center;padding:4px 0 8px;">\n      <a href="{{store_url}}"\n        style="display:inline-block;background:#ff9900;color:#111;font-size:14px;font-weight:700;\n        text-decoration:none;padding:10px 36px;border-radius:3px;border:1px solid #e47911;">\n        Visit Our Store\n      </a>\n    </div>\n\n  </div>\n\n  <!-- Footer -->\n  <div style="text-align:center;padding:18px 0 8px;">\n    <p style="margin:0;font-size:12px;color:#888;">\n      {{store_name}} &nbsp;|&nbsp;\n      <a href="mailto:{{store_email}}" style="color:#0066c0;text-decoration:none;">{{store_email}}</a>\n      &nbsp;|&nbsp;\n      <a href="{{store_url}}" style="color:#0066c0;text-decoration:none;">{{store_url}}</a>\n    </p>\n  </div>\n\n</div>\n</div>',
        'trigger_type': 'order_placed',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Order Confirmation — Luxury Style',
        'category': 'order',
        'status': 'active',
        'subject': 'Your order {{order_id}} is confirmed — {{store_name}}',
        'preheader': 'Your order has been received and is being carefully processed.',
        'body_html': '<div style="background:#f9f5ee;padding:0;font-family:Georgia,\'Times New Roman\',serif;color:#1a1a1a;">\n<div style="max-width:560px;margin:0 auto;">\n\n  <!-- Header -->\n  <div style="padding:36px 48px 28px;text-align:center;border-bottom:1px solid #e0d8cc;">\n    <p style="margin:0 0 8px;font-size:10px;font-weight:700;color:#b8622a;text-transform:uppercase;letter-spacing:3px;font-family:Arial,sans-serif;">Established Excellence</p>\n    <p style="margin:0;font-size:26px;font-weight:700;color:#1a1a1a;letter-spacing:-.3px;">{{store_name}}</p>\n  </div>\n\n  <!-- Confirmed Block -->\n  <div style="padding:36px 48px 28px;text-align:center;border-bottom:1px solid #e0d8cc;">\n    <p style="margin:0 0 12px;font-size:10px;font-weight:700;color:#b8622a;text-transform:uppercase;letter-spacing:3px;font-family:Arial,sans-serif;">Order Confirmed</p>\n    <h1 style="margin:0 0 14px;font-size:30px;font-weight:700;color:#1a1a1a;letter-spacing:-.5px;">Thank you, {{customer_name}}</h1>\n    <p style="margin:0;font-size:14px;color:#777;line-height:1.7;font-family:Arial,sans-serif;">Your order has been received and is being carefully processed.<br>We will notify you of any updates.</p>\n  </div>\n\n  <!-- Reference + Date -->\n  <table width="100%" cellpadding="0" cellspacing="0" style="border-bottom:1px solid #e0d8cc;">\n    <tr>\n      <td style="padding:22px 48px;border-right:1px solid #e0d8cc;">\n        <p style="margin:0 0 6px;font-size:9px;font-weight:700;color:#b8622a;text-transform:uppercase;letter-spacing:2.5px;font-family:Arial,sans-serif;">Reference</p>\n        <p style="margin:0;font-size:20px;font-weight:700;color:#1a1a1a;">{{order_id}}</p>\n      </td>\n      <td style="padding:22px 48px;text-align:right;">\n        <p style="margin:0 0 6px;font-size:9px;font-weight:700;color:#b8622a;text-transform:uppercase;letter-spacing:2.5px;font-family:Arial,sans-serif;">Date</p>\n        <p style="margin:0;font-size:14px;font-weight:700;color:#1a1a1a;text-transform:uppercase;letter-spacing:.5px;font-family:Arial,sans-serif;">{{order_date}}</p>\n      </td>\n    </tr>\n  </table>\n\n  <!-- Your Selection -->\n  <div style="padding:22px 48px;border-bottom:1px solid #e0d8cc;">\n    <p style="margin:0 0 16px;font-size:9px;font-weight:700;color:#b8622a;text-transform:uppercase;letter-spacing:2.5px;font-family:Arial,sans-serif;">Your Selection</p>\n    <table width="100%" cellpadding="0" cellspacing="0">\n      <tr>\n        \n        <td style="vertical-align:top;padding-top:4px;">\n          <p style="margin:0 0 6px;font-size:14px;font-weight:700;color:#1a1a1a;">{{order_items}}</p>\n          <p style="margin:0;font-size:10px;font-weight:700;color:#b8622a;text-transform:uppercase;letter-spacing:2px;font-family:Arial,sans-serif;">{{payment_status}}</p>\n        </td>\n        <td style="vertical-align:top;padding-top:4px;text-align:right;white-space:nowrap;">\n          <p style="margin:0;font-size:15px;font-weight:700;color:#b8622a;">{{order_total}}</p>\n        </td>\n      </tr>\n    </table>\n  </div>\n\n  <!-- Order Summary -->\n  <div style="padding:22px 48px;border-bottom:1px solid #e0d8cc;">\n    <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial,sans-serif;">\n      <tr>\n        <td style="padding:7px 0;font-size:13px;color:#666;border-bottom:1px solid #ede7da;">Subtotal</td>\n        <td style="padding:7px 0;font-size:13px;color:#1a1a1a;text-align:right;border-bottom:1px solid #ede7da;">{{subtotal}}</td>\n      </tr>\n      {{#if discount_amount}}\n      <tr>\n        <td style="padding:7px 0;font-size:13px;color:#b8622a;border-bottom:1px solid #ede7da;">Discount</td>\n        <td style="padding:7px 0;font-size:13px;color:#b8622a;text-align:right;border-bottom:1px solid #ede7da;">– {{discount_amount}}</td>\n      </tr>\n      {{/if}}\n      {{#if shipping_amount}}\n      <tr>\n        <td style="padding:7px 0;font-size:13px;color:#666;border-bottom:1px solid #ede7da;">Shipping</td>\n        <td style="padding:7px 0;font-size:13px;color:#1a1a1a;text-align:right;border-bottom:1px solid #ede7da;">{{shipping_amount}}</td>\n      </tr>\n      {{/if}}\n      {{#if tax_amount}}\n      <tr>\n        <td style="padding:7px 0;font-size:13px;color:#666;border-bottom:1px solid #ede7da;">Tax</td>\n        <td style="padding:7px 0;font-size:13px;color:#1a1a1a;text-align:right;border-bottom:1px solid #ede7da;">{{tax_amount}}</td>\n      </tr>\n      {{/if}}\n      <tr>\n        <td style="padding:14px 0 0;font-size:16px;font-weight:700;color:#1a1a1a;">Total Charged</td>\n        <td style="padding:14px 0 0;font-size:18px;font-weight:700;color:#b8622a;text-align:right;">{{order_total}}</td>\n      </tr>\n    </table>\n  </div>\n\n  <!-- Shipping Address -->\n  <table width="100%" cellpadding="0" cellspacing="0" style="border-bottom:1px solid #e0d8cc;">\n    <tr>\n      <td style="padding:22px 48px;vertical-align:top;border-right:1px solid #e0d8cc;width:50%;">\n        <p style="margin:0 0 10px;font-size:9px;font-weight:700;color:#b8622a;text-transform:uppercase;letter-spacing:2.5px;font-family:Arial,sans-serif;">Shipping To</p>\n        <p style="margin:0 0 2px;font-size:14px;font-weight:700;color:#1a1a1a;">{{customer_name}}</p>\n        <p style="margin:0;font-size:13px;color:#666;line-height:1.7;font-family:Arial,sans-serif;">{{shipping_full_address}}</p>\n      </td>\n      <td style="padding:22px 48px;vertical-align:top;">\n        <p style="margin:0 0 10px;font-size:9px;font-weight:700;color:#b8622a;text-transform:uppercase;letter-spacing:2.5px;font-family:Arial,sans-serif;">Payment</p>\n        <p style="margin:0 0 2px;font-size:13px;color:#1a1a1a;font-family:Arial,sans-serif;">{{payment_method}}</p>\n        <p style="margin:8px 0 0;font-size:9px;font-weight:700;color:#b8622a;text-transform:uppercase;letter-spacing:2.5px;font-family:Arial,sans-serif;">Contact</p>\n        <p style="margin:6px 0 0;font-size:13px;color:#666;font-family:Arial,sans-serif;">{{customer_email}}</p>\n      </td>\n    </tr>\n  </table>\n\n  <!-- Footer -->\n  <div style="background:#3d2314;padding:18px 48px;text-align:center;">\n    <p style="margin:0;font-size:11px;color:#c9a882;text-transform:uppercase;letter-spacing:2px;font-family:Arial,sans-serif;">\n      {{store_name}} &nbsp;&middot;&nbsp;\n      <a href="mailto:{{store_email}}" style="color:#c9a882;text-decoration:underline;">{{store_email}}</a>\n    </p>\n  </div>\n\n</div>\n</div>',
        'trigger_type': 'order_placed',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Order Confirmation — Shopify',
        'category': 'order',
        'status': 'active',
        'subject': 'Your order {{order_id}} is confirmed',
        'preheader': "We've received your order and it's being prepared.",
        'body_html': '<div style="background:#f6f6f6;padding:40px 0;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Helvetica,Arial,sans-serif;color:#1a1a1a;">\n<div style="max-width:560px;margin:0 auto;padding:0 20px;">\n\n  <!-- White Card (header inside) -->\n  <div style="background:#ffffff;border-radius:4px;overflow:hidden;">\n\n    <!-- Store name header -->\n    <table width="100%" cellpadding="0" cellspacing="0" style="padding:20px 24px 0;">\n      <tr>\n        <td style="font-size:16px;font-weight:700;color:#1a1a1a;">{{store_name}}</td>\n        <td align="right" style="font-size:13px;color:#6b7280;font-weight:600;">Order Confirmation</td>\n      </tr>\n    </table>\n    <div style="height:3px;background:#008060;border-radius:2px;margin:10px 24px 0;"></div>\n    <!-- Hero section -->\n    <div style="padding:28px 24px 20px;text-align:center;">\n      <div style="width:52px;height:52px;background:#d1fae5;border-radius:50%;margin:0 auto 14px;display:flex;align-items:center;justify-content:center;">\n        <span style="font-size:24px;color:#008060;">&#10003;</span>\n      </div>\n      <h1 style="margin:0 0 8px;font-size:22px;font-weight:700;color:#1a1a1a;">Your order is confirmed!</h1>\n      <p style="margin:0;font-size:14px;color:#6b7280;">Hi {{customer_name}}, we&#39;ve received your order and it&#39;s being prepared.</p>\n    </div>\n    <!-- Order meta -->\n    <table width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid #e5e7eb;border-bottom:1px solid #e5e7eb;">\n      <tr>\n        <td style="padding:16px 24px;border-right:1px solid #e5e7eb;">\n          <p style="margin:0 0 4px;font-size:10px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:.8px;">Order Number</p>\n          <p style="margin:0;font-size:17px;font-weight:700;color:#1a1a1a;">{{order_id}}</p>\n        </td>\n        <td style="padding:16px 24px;text-align:right;">\n          <p style="margin:0 0 4px;font-size:10px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:.8px;">Date</p>\n          <p style="margin:0;font-size:14px;font-weight:600;color:#1a1a1a;">{{order_date}}</p>\n        </td>\n      </tr>\n    </table>\n    <!-- Items Ordered section -->\n    <div style="margin:0 20px;border:1px solid #e5e7eb;border-radius:4px;overflow:hidden;">\n      <div style="padding:10px 16px;border-bottom:1px solid #e5e7eb;background:#f9fafb;">\n        <p style="margin:0;font-size:10px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:.8px;">Items Ordered</p>\n      </div>\n      <div style="padding:0 16px;">{{order_items}}</div>\n    </div>\n\n    <!-- Subtotal + Total -->\n    <table width="100%" cellpadding="0" cellspacing="0" style="margin-top:2px;border-bottom:1px solid #e5e7eb;">\n      <tr>\n        <td style="padding:12px 20px;font-size:14px;color:#666;">Subtotal</td>\n        <td style="padding:12px 20px;font-size:14px;color:#1a1a1a;text-align:right;">{{subtotal}}</td>\n      </tr>\n      <tr>\n        <td colspan="2" style="padding:0 20px;">\n          {{#if discount_amount}}<table width="100%" cellpadding="0" cellspacing="0">\n          <tr>\n            <td style="padding:6px 0;font-size:13px;color:#008060;">Discount</td>\n            <td style="padding:6px 0;font-size:13px;color:#008060;text-align:right;">-{{discount_amount}}</td>\n          </tr>\n          </table>{{/if}}\n        </td>\n      </tr>\n      <tr>\n        <td style="padding:12px 20px;font-size:15px;font-weight:700;color:#1a1a1a;">Total Charged</td>\n        <td style="padding:12px 20px;font-size:17px;font-weight:700;color:#008060;text-align:right;">{{order_total}}</td>\n      </tr>\n    </table>\n\n    <!-- Shipping / Contact / Payment -->\n    <table width="100%" cellpadding="0" cellspacing="0" style="margin:0;border-top:1px solid #e5e7eb;">\n      <tr>\n        <td style="padding:18px 20px;vertical-align:top;width:50%;border-right:1px solid #e5e7eb;">\n          <p style="margin:0 0 8px;font-size:10px;font-weight:700;color:#999;text-transform:uppercase;letter-spacing:.8px;">Shipping To</p>\n          <p style="margin:0 0 2px;font-size:14px;font-weight:700;color:#1a1a1a;">{{customer_name}}</p>\n          <p style="margin:0;font-size:13px;color:#555;line-height:1.6;">{{shipping_full_address}}</p>\n        </td>\n        <td style="padding:18px 20px;vertical-align:top;">\n          <p style="margin:0 0 8px;font-size:10px;font-weight:700;color:#999;text-transform:uppercase;letter-spacing:.8px;">Contact</p>\n          <p style="margin:0 0 2px;font-size:13px;color:#008060;">{{customer_email}}</p>\n          <p style="margin:0 0 16px;font-size:13px;color:#555;">{{customer_phone}}</p>\n          <p style="margin:0 0 8px;font-size:10px;font-weight:700;color:#999;text-transform:uppercase;letter-spacing:.8px;">Payment</p>\n          <p style="margin:0 0 6px;font-size:13px;color:#555;">{{payment_method}}</p>\n          <span style="display:inline-block;background:#e6f4f0;color:#008060;font-size:12px;font-weight:600;padding:3px 10px;border-radius:20px;">{{payment_status}}</span>\n        </td>\n      </tr>\n    </table>\n\n    <!-- Status Banner -->\n    <div style="background:#e6f4f0;padding:14px 32px;text-align:center;">\n      <p style="margin:0;font-size:14px;color:#1a1a1a;">\n        <strong>Status: {{payment_status}}</strong> &mdash; Our team is preparing your order.\n      </p>\n    </div>\n\n  </div>\n\n  <!-- Footer -->\n  <div style="text-align:center;padding:22px 0 10px;">\n    <p style="margin:0;font-size:13px;color:#999;">\n      {{store_name}} &nbsp;&middot;&nbsp;\n      <a href="mailto:{{store_email}}" style="color:#008060;text-decoration:none;">{{store_email}}</a>\n    </p>\n  </div>\n\n</div>\n</div>',
        'trigger_type': 'order_placed',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': True,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Refund Confirmation — Amazon Style',
        'category': 'refund',
        'status': 'active',
        'subject': 'Your {{store_name}} refund is confirmed',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f0f2f2;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f0f2f2;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#232F3E;padding:20px 40px;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:20px;font-weight:700;color:#FF9900;">{{store_name}}</td>\n  <td align="right" style="font-size:13px;color:#aab7c4;">Refund Confirmation</td>\n</tr></table>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<p style="margin:0 0 16px;font-size:16px;color:#111;font-weight:600;">Hello {{customer_name}},</p>\n<p style="margin:0 0 24px;font-size:14px;color:#333;">Your refund for order <strong>#{{order_id}}</strong> has been processed successfully.</p>\n\n<!-- Refund box -->\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;margin-bottom:24px;background:#f7f7f7;">\n  <table width="100%" cellpadding="0" cellspacing="0">\n    <tr>\n      <td style="font-size:14px;color:#555;">Refund Amount</td>\n      <td align="right" style="font-size:22px;font-weight:700;color:#b12704;">{{refund_amount}}</td>\n    </tr>\n    <tr><td colspan="2" style="padding:10px 0;border-top:1px solid #ddd;margin-top:10px;"></td></tr>\n    <tr>\n      <td style="font-size:13px;color:#767676;">Refunded to</td>\n      <td align="right" style="font-size:13px;color:#111;">{{refund_method}}</td>\n    </tr>\n    <tr>\n      <td style="font-size:13px;color:#767676;padding-top:6px;">Original Order</td>\n      <td align="right" style="font-size:13px;color:#111;padding-top:6px;">#{{order_id}}</td>\n    </tr>\n  </table>\n</div>\n\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;margin-bottom:24px;">\n  <p style="margin:0 0 14px;font-size:14px;font-weight:600;color:#111;">Refunded Items</p>\n  {{order_items}}\n</div>\n\n<p style="font-size:13px;color:#555;margin:0;">Please allow 3–5 business days for the refund to appear in your account.</p>\n</td></tr>\n<tr><td style="background:#232F3E;padding:16px 40px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#aab7c4;">© {{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'manual',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Refund Confirmation — Luxury Style',
        'category': 'refund',
        'status': 'active',
        'subject': 'Refund Confirmation — Order #{{order_id}}',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#ede8df;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#ede8df;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#f9f5ee;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#f9f5ee;padding:40px 48px 28px;text-align:center;border-bottom:1px solid #e8ddd0;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;">Refund Notice</p>\n<h1 style="margin:0;font-size:28px;font-weight:400;color:#2c1810;font-family:Georgia,serif;letter-spacing:1px;">{{store_name}}</h1>\n</td></tr>\n<tr><td style="background:#f9f5ee;padding:36px 48px;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;text-align:center;">REFUND CONFIRMED</p>\n<h2 style="margin:0 0 24px;font-size:22px;font-weight:400;color:#2c1810;font-family:Georgia,serif;text-align:center;">Dear {{customer_name}},</h2>\n<p style="font-size:15px;color:#5c3d2e;line-height:1.7;margin:0 0 28px;text-align:center;">We have processed your refund. We hope to have the opportunity<br>to serve you again in the future.</p>\n\n<!-- Refund details -->\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">\n<tr>\n  <td width="50%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Order Reference</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#2c1810;font-family:Georgia,serif;">#{{order_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="46%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Refund Amount</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#b8622a;font-family:Georgia,serif;">{{refund_amount}}</p>\n  </td>\n</tr>\n</table>\n\n<div style="border:1px solid #ddd2be;border-radius:4px;padding:16px 20px;margin-bottom:24px;background:#fdf9f3;">\n  <table width="100%" cellpadding="0" cellspacing="0">\n    <tr>\n      <td style="font-size:13px;color:#7a5c46;font-family:Georgia,serif;">Refunded to</td>\n      <td align="right" style="font-size:13px;color:#2c1810;font-weight:600;font-family:Georgia,serif;">{{refund_method}}</td>\n    </tr>\n  </table>\n</div>\n\n<div style="border-top:1px solid #e8ddd0;padding-top:20px;">\n  <p style="margin:0 0 12px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Items Refunded</p>\n  {{order_items}}\n</div>\n</td></tr>\n<tr><td style="background:#3d2314;padding:24px 48px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#c4a882;letter-spacing:0.5px;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'manual',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Refund Confirmation — Shopify',
        'category': 'refund',
        'status': 'active',
        'subject': 'Your refund for order #{{order_id}} has been processed',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f4f4f4;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f4f4f4;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#ffffff;padding:32px 40px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:18px;font-weight:700;color:#1a1a1a;">{{store_name}}</td>\n  <td align="right" style="font-size:14px;color:#6b7280;font-weight:600;">Refund Processed</td>\n</tr></table>\n<div style="height:3px;background:#008060;border-radius:2px;margin-top:12px;"></div>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<div style="text-align:center;margin-bottom:28px;">\n  <div style="width:56px;height:56px;background:#d1fae5;border-radius:50%;margin:0 auto 16px;display:flex;align-items:center;justify-content:center;">\n    <span style="font-size:26px;">💚</span>\n  </div>\n  <h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1a1a1a;">Your refund is on the way!</h1>\n  <p style="margin:0;font-size:15px;color:#6b7280;">Hi {{customer_name}}, your refund has been processed successfully.</p>\n</div>\n\n<!-- Refund amount box -->\n<div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:20px 24px;margin-bottom:24px;text-align:center;">\n  <p style="margin:0 0 6px;font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;">Refund Amount</p>\n  <p style="margin:0 0 6px;font-size:32px;font-weight:700;color:#008060;">{{refund_amount}}</p>\n  <p style="margin:0;font-size:13px;color:#6b7280;">Refunded to: <strong>{{refund_method}}</strong></p>\n</div>\n\n<!-- Order info bar -->\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">\n<tr>\n  <td width="48%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Order Number</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#1a1a1a;">#{{order_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="48%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Date</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#1a1a1a;">{{order_date}}</p>\n  </td>\n</tr>\n</table>\n\n<p style="font-size:13px;color:#6b7280;margin:0 0 8px;">Please allow 3–5 business days for the refund to appear in your account. If you have any questions, reply to this email.</p>\n\n<!-- Items -->\n<p style="font-size:13px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin:20px 0 12px;">Refunded Items</p>\n{{order_items}}\n</td></tr>\n<tr><td style="background:#f9fafb;padding:20px 40px;text-align:center;border-top:1px solid #e5e7eb;">\n<p style="margin:0;font-size:12px;color:#9ca3af;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'manual',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': True,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Shipping Notification — Amazon Style',
        'category': 'shipping',
        'status': 'active',
        'subject': 'Your {{store_name}} shipment is on the way',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f0f2f2;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f0f2f2;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#232F3E;padding:20px 40px;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:20px;font-weight:700;color:#FF9900;">{{store_name}}</td>\n  <td align="right" style="font-size:13px;color:#aab7c4;">Shipping Update</td>\n</tr></table>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<!-- Info bar -->\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;background:#f7f7f7;border-radius:4px;">\n<tr>\n  <td width="33%" style="text-align:center;padding:14px 8px;">\n    <p style="margin:0 0 3px;font-size:11px;color:#767676;">ORDER PLACED</p>\n    <p style="margin:0;font-size:13px;font-weight:600;color:#111;">{{order_date}}</p>\n  </td>\n  <td width="33%" style="text-align:center;padding:14px 8px;border-left:1px solid #ddd;">\n    <p style="margin:0 0 3px;font-size:11px;color:#767676;">ORDER #</p>\n    <p style="margin:0;font-size:13px;font-weight:600;color:#111;">{{order_id}}</p>\n  </td>\n  <td width="34%" style="text-align:center;padding:14px 8px;border-left:1px solid #ddd;">\n    <p style="margin:0 0 3px;font-size:11px;color:#767676;">ORDER TOTAL</p>\n    <p style="margin:0;font-size:13px;font-weight:600;color:#b12704;">{{order_total}}</p>\n  </td>\n</tr>\n</table>\n\n<p style="margin:0 0 16px;font-size:16px;color:#111;font-weight:600;">Hello {{customer_name}},</p>\n<p style="margin:0 0 24px;font-size:14px;color:#333;">Your shipment is on the way and arriving soon.</p>\n\n<!-- Tracking box -->\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;margin-bottom:24px;">\n  <p style="margin:0 0 4px;font-size:13px;color:#767676;">Tracking Number</p>\n  <p style="margin:0 0 4px;font-size:18px;font-weight:700;color:#111;letter-spacing:0.5px;">{{tracking_number}}</p>\n  <p style="margin:0 0 16px;font-size:13px;color:#555;">Carrier: <strong>{{carrier}}</strong> &nbsp;·&nbsp; Est. Delivery: <strong>{{estimated_delivery}}</strong></p>\n  <table width="100%" cellpadding="0" cellspacing="0"><tr>\n    <td><a href="{{tracking_url}}" style="display:inline-block;background:#FF9900;color:#111;font-size:14px;font-weight:700;text-decoration:none;padding:10px 24px;border-radius:4px;border:1px solid #e68a00;">Track Package</a></td>\n  </tr></table>\n</div>\n\n<!-- Items -->\n<div style="border:1px solid #ddd;border-radius:4px;padding:20px 24px;margin-bottom:24px;">\n  <p style="margin:0 0 14px;font-size:14px;font-weight:600;color:#111;">Shipment Contents</p>\n  {{order_items}}\n</div>\n</td></tr>\n<tr><td style="background:#232F3E;padding:16px 40px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#aab7c4;">© {{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'tracking_added',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Shipping Notification — Luxury Style',
        'category': 'shipping',
        'status': 'active',
        'subject': 'Your order from {{store_name}} has shipped',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#ede8df;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#ede8df;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#f9f5ee;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#f9f5ee;padding:40px 48px 28px;text-align:center;border-bottom:1px solid #e8ddd0;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;">Shipping Notification</p>\n<h1 style="margin:0;font-size:28px;font-weight:400;color:#2c1810;font-family:Georgia,serif;letter-spacing:1px;">{{store_name}}</h1>\n</td></tr>\n<tr><td style="background:#f9f5ee;padding:36px 48px;">\n<p style="margin:0 0 6px;font-size:10px;letter-spacing:3px;color:#b8622a;text-transform:uppercase;font-family:Georgia,serif;text-align:center;">YOUR ORDER HAS SHIPPED</p>\n<h2 style="margin:0 0 24px;font-size:22px;font-weight:400;color:#2c1810;font-family:Georgia,serif;text-align:center;">Dear {{customer_name}},</h2>\n<p style="font-size:15px;color:#5c3d2e;line-height:1.7;margin:0 0 28px;text-align:center;">We are pleased to inform you that your order is on its way.<br>Below are your shipment details.</p>\n\n<!-- Reference columns -->\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">\n<tr>\n  <td width="50%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Order Reference</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#2c1810;font-family:Georgia,serif;">#{{order_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="46%" style="padding:16px 20px;background:#f0e8d8;border-radius:4px;text-align:center;">\n    <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Est. Delivery</p>\n    <p style="margin:0;font-size:16px;font-weight:700;color:#2c1810;font-family:Georgia,serif;">{{estimated_delivery}}</p>\n  </td>\n</tr>\n</table>\n\n<!-- Tracking -->\n<div style="border:1px solid #ddd2be;border-radius:4px;padding:20px 24px;margin-bottom:24px;text-align:center;background:#fdf9f3;">\n  <p style="margin:0 0 4px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">Tracking Number</p>\n  <p style="margin:0 0 4px;font-size:20px;font-weight:700;color:#2c1810;font-family:Georgia,serif;letter-spacing:2px;">{{tracking_number}}</p>\n  <p style="margin:0 0 16px;font-size:13px;color:#7a5c46;">via {{carrier}}</p>\n  <a href="{{tracking_url}}" style="display:inline-block;background:#b8622a;color:#ffffff;font-size:13px;letter-spacing:1px;text-decoration:none;padding:11px 30px;border-radius:2px;text-transform:uppercase;">Track Your Order</a>\n</div>\n\n<div style="border-top:1px solid #e8ddd0;padding-top:20px;">\n  <p style="margin:0 0 12px;font-size:10px;letter-spacing:2px;color:#b8622a;text-transform:uppercase;">YOUR SELECTION</p>\n  {{order_items}}\n</div>\n</td></tr>\n<tr><td style="background:#3d2314;padding:24px 48px;text-align:center;">\n<p style="margin:0;font-size:12px;color:#c4a882;letter-spacing:0.5px;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'tracking_added',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': False,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
    {
        'name': 'Shipping Notification — Shopify',
        'category': 'shipping',
        'status': 'active',
        'subject': 'Your order #{{order_id}} has shipped!',
        'preheader': '',
        'body_html': '<!DOCTYPE html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n<style>body{margin:0;padding:0;background:#f4f4f4;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif}\na{color:inherit}</style></head>\n<body style="background:#f4f4f4;margin:0;padding:32px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">\n<tr><td style="background:#ffffff;padding:32px 40px 0;">\n<table width="100%" cellpadding="0" cellspacing="0"><tr>\n  <td style="font-size:18px;font-weight:700;color:#1a1a1a;">{{store_name}}</td>\n  <td align="right" style="font-size:14px;color:#6b7280;font-weight:600;">Shipping Notification</td>\n</tr></table>\n<div style="height:3px;background:#008060;border-radius:2px;margin-top:12px;"></div>\n</td></tr>\n<tr><td style="padding:32px 40px;">\n<div style="text-align:center;margin-bottom:28px;">\n  <div style="width:56px;height:56px;background:#d1fae5;border-radius:50%;margin:0 auto 16px;display:flex;align-items:center;justify-content:center;">\n    <span style="font-size:26px;">📦</span>\n  </div>\n  <h1 style="margin:0 0 8px;font-size:24px;font-weight:700;color:#1a1a1a;">Your order is on its way!</h1>\n  <p style="margin:0;font-size:15px;color:#6b7280;">Hi {{customer_name}}, great news — your package has shipped.</p>\n</div>\n\n<!-- Tracking box -->\n<div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:20px 24px;margin-bottom:24px;text-align:center;">\n  <p style="margin:0 0 6px;font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;">Tracking Number</p>\n  <p style="margin:0 0 12px;font-size:20px;font-weight:700;color:#1a1a1a;letter-spacing:1px;">{{tracking_number}}</p>\n  <p style="margin:0 0 16px;font-size:13px;color:#6b7280;">Carrier: <strong>{{carrier}}</strong> &nbsp;|&nbsp; Est. Delivery: <strong>{{estimated_delivery}}</strong></p>\n  <a href="{{tracking_url}}" style="display:inline-block;background:#008060;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;padding:11px 28px;border-radius:6px;">Track Package</a>\n</div>\n\n<!-- Order info bar -->\n<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">\n<tr>\n  <td width="33%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Order</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#1a1a1a;">#{{order_id}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="29%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Date</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#1a1a1a;">{{order_date}}</p>\n  </td>\n  <td width="4%"></td>\n  <td width="30%" style="text-align:center;padding:14px 8px;background:#f9fafb;border-radius:6px;">\n    <p style="margin:0 0 4px;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.5px;">Total</p>\n    <p style="margin:0;font-size:14px;font-weight:600;color:#008060;">{{order_total}}</p>\n  </td>\n</tr>\n</table>\n\n<!-- Items -->\n<p style="font-size:13px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 12px;">Items Shipped</p>\n{{order_items}}\n</td></tr>\n<tr><td style="background:#f9fafb;padding:20px 40px;text-align:center;border-top:1px solid #e5e7eb;">\n<p style="margin:0;font-size:12px;color:#9ca3af;">{{store_name}} &nbsp;·&nbsp; {{store_email}}</p>\n</td></tr>\n</table>\n</td></tr></table>\n</body></html>',
        'trigger_type': 'tracking_added',
        'trigger_delay_minutes': 0,
        'working_hours_only': False,
        'throttle_per_day': False,
        'is_category_default': True,
        'is_global': False,
        'description': '',
        'tags': [],
        'from_email': None,
        'sender_name': '',
        'reply_to': None,
        'cc_emails': [],
        'bcc_emails': [],
        'use_default_signature': True,
        'custom_signature': '',
        'footer': '',
    },
]
