# Generated by Django 4.2.30 on 2026-05-21 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('admin', 'Admin (Tenant Owner)'), ('vendor', 'Vendor'), ('employee', 'Team Member')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('order', 'Order'), ('vendor', 'Vendor'), ('tracking', 'Tracking'), ('email', 'Email'), ('chat', 'Chat'), ('task', 'Task'), ('store', 'Store'), ('payment', 'Payment'), ('system', 'System'), ('ai', 'AI')], db_index=True, default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=80)),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('action_label', models.CharField(blank=True, default='', max_length=60)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_email_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_task_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['recipient', 'audience', '-created_at'], name='notificatio_recipie_24732c_idx')],
            },
        ),
    ]
